import React, { useEffect, useState } from 'react';
import { PageShell } from "@/components/PageShell";
import { Button } from "@/components/ui/button";
import { 
  Bell, 
  CheckCheck, 
  Trash2, 
  Info, 
  CheckCircle2, 
  XCircle,
  Clock,
  UserCheck,
  Trophy,
  Ticket
} from "lucide-react";
import { 
  getNotifications, 
  markAsRead, 
  markAllAsRead, 
  deleteNotification, 
  Notification,
  NotificationType
} from "@/services/notificationService";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";
import { formatDistanceToNow } from "date-fns";
import { useLanguage } from "@/contexts/LanguageContext";
import { useAuth } from '@/contexts/AuthContext';
import { AdminLayout } from "@/components/AdminLayout";

export default function Notifications() {
  const { user } = useAuth();
  const { t } = useLanguage();
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  const isAdminOrStaff = user?.role === 'admin' || user?.role === 'lottery_staff';

  const fetchNotifications = async () => {
    try {
      const data = await getNotifications();
      setNotifications(data);
    } catch (error) {
      console.error('Failed to fetch notifications:', error);
      toast({
        title: "Error",
        description: "Failed to load notifications.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchNotifications();
  }, []);

  const handleMarkAsRead = async (id: string) => {
    try {
      await markAsRead(id);
      setNotifications(notifications.map(n => n.id === id ? { ...n, is_read: true } : n));
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to update notification.",
        variant: "destructive",
      });
    }
  };

  const handleMarkAllAsRead = async () => {
    try {
      await markAllAsRead();
      setNotifications(notifications.map(n => ({ ...n, is_read: true })));
      toast({
        title: "Success",
        description: "All notifications marked as read.",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to update notifications.",
        variant: "destructive",
      });
    }
  };

  const handleDelete = async (id: string) => {
    try {
      await deleteNotification(id);
      setNotifications(notifications.filter(n => n.id !== id));
      toast({
        title: "Success",
        description: "Notification deleted.",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to delete notification.",
        variant: "destructive",
      });
    }
  };

  const getIcon = (type: NotificationType) => {
    switch (type) {
      case 'registration':      return <UserCheck    className="h-5 w-5 text-teal-500" />;
      case 'payment_pending':   return <Clock        className="h-5 w-5 text-amber-500" />;
      case 'payment_approved':  return <CheckCircle2 className="h-5 w-5 text-green-500" />;
      case 'payment_rejected':  return <XCircle      className="h-5 w-5 text-red-500" />;
      case 'ticket_assigned':   return <Ticket       className="h-5 w-5 text-teal-500" />;
      case 'lottery_result':    return <Trophy       className="h-5 w-5 text-yellow-500" />;
      case 'reminder':          return <Bell         className="h-5 w-5 text-amber-500" />;
      case 'system_update':     return <Info         className="h-5 w-5 text-slate-500" />;
    }
  };

  const translateTitle = (title: string) => {
    // English
    if (title === "Payment Under Review") return t("payUnderReviewTitle") || title;
    if (title === "Ticket Assigned") return t("ticketAssignedTitle") || title;
    if (title === "Lottery Result") return t("lotteryResultTitle") || title;
    if (title === "Payment Approved") return t("paymentApprovedTitle") || title;
    if (title === "Payment Rejected") return t("payRejectedTitle") || title;
    
    // Amharic (Generated by backend)
    if (title === "ክፍያ በግምገማ ላይ ነው") return t("payUnderReviewTitle") || title;
    if (title === "ቲኬት ተሰጥቷል") return t("ticketAssignedTitle") || title;
    if (title === "የሎተሪ ውጤት") return t("lotteryResultTitle") || title;
    if (title === "ክፍያ ፀድቋል") return t("paymentApprovedTitle") || title;
    if (title === "ክፍያ ውድቅ ተደርጓል") return t("payRejectedTitle") || title;
    
    // Oromo
    if (title === "Kaffalti Keessan Madaalamaa Jira") return t("payUnderReviewTitle") || title;
    if (title === "Tikeetiin Kennamaniiru") return t("ticketAssignedTitle") || title;
    if (title === "Bu'aa Loterii") return t("lotteryResultTitle") || title;
    if (title === "Kaffalti Mirkanaa'eera") return t("paymentApprovedTitle") || title;
    if (title === "Kaffaltiin Kufeera") return t("payRejectedTitle") || title;
    
    return title;
  };

  const translateMessage = (msg: string) => {
    if (msg.includes("is under review") || msg.includes("በግምገማ ላይ ነው") || msg.includes("qulqulla'aa jira")) {
      const tickets = msg.match(/(#\d+(?:,\s*#\d+)*)/)?.[1] || "";
      return t("payUnderReviewText")?.replace("{tickets}", tickets) || msg;
    }
    if (msg.includes("Your lottery ticket") || msg.includes("ተመድቦልዎታል") || msg.includes("isiniif kennamedha")) {
      return t("ticketAssignedText") || msg;
    }
    if (msg.includes("ክፍያዎ ውድቅ ተደርጓል") || (msg.includes("Your payment for tickets") && msg.includes("rejected")) || msg.includes("kufeera")) {
       const tickets = msg.match(/(#\d+(?:,\s*#\d+)*)/)?.[1] || "";
       let reason = msg.split(/ምክንያት:|Reason:|Sababa:/i)[1]?.trim() || "";
       if (reason) {
          return t("payRejectedMsg")?.replace("{tickets}", tickets).replace("{rejection_reason}", reason) || msg;
       }
    }
    return msg;
  };

  const content = (
    <div className={cn(
      "container mx-auto px-4 lg:px-8 max-w-3xl animate-fade-in-up",
      isAdminOrStaff && "py-6"
    )}>
      <div className="flex items-center justify-between mb-8">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-primary/10 rounded-lg">
            <Bell className="h-6 w-6 text-primary" />
          </div>
          <h1 className="text-3xl font-bold text-foreground">{t("notifications")}</h1>
        </div>
        {notifications.some(n => !n.is_read) && (
          <Button variant="outline" size="sm" onClick={handleMarkAllAsRead}>
            <CheckCheck className="h-4 w-4 mr-2" />
            {t("notifMarkAllAsRead")}
          </Button>
        )}
      </div>

      {loading ? (
        <div className="flex flex-col items-center justify-center py-20 space-y-4">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          <p className="text-muted-foreground">{t("notifLoading")}</p>
        </div>
      ) : notifications.length === 0 ? (
        <div className="bg-card rounded-xl border border-dashed p-12 text-center">
          <div className="w-16 h-16 bg-muted rounded-full flex items-center justify-center mx-auto mb-4">
            <Bell className="h-8 w-8 text-muted-foreground" />
          </div>
          <h3 className="text-lg font-medium text-foreground mb-1">{t("notifNoNotificationsYet")}</h3>
          <p className="text-muted-foreground">{t("notifWhenUpdatesAppear")}</p>
        </div>
      ) : (
        <div className="space-y-4">
          {notifications.map((notification) => (
            <div 
              key={notification.id}
              className={cn(
                "group relative bg-card rounded-xl border p-4 transition-all hover:shadow-md",
                !notification.is_read && "border-primary/30 bg-primary/5"
              )}
            >
              <div className="flex gap-4">
                <div className="mt-1">
                  {getIcon(notification.type)}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-2">
                    <h3 className={cn(
                      "font-semibold text-foreground leading-tight",
                      !notification.is_read && "text-primary"
                    )}>
                      {translateTitle(notification.title)}
                    </h3>
                    <span className="text-xs text-muted-foreground whitespace-nowrap flex items-center gap-1">
                      <Clock className="h-3 w-3" />
                      {formatDistanceToNow(new Date(notification.created_at), { addSuffix: true })}
                    </span>
                  </div>
                  <p className="text-sm text-muted-foreground mt-1 line-clamp-2">
                    {translateMessage(notification.message)}
                  </p>
                  <div className="flex items-center gap-3 mt-3">
                    {!notification.is_read && (
                      <button 
                        onClick={() => handleMarkAsRead(notification.id)}
                        className="text-xs font-medium text-primary hover:underline"
                      >
                        {t("notifMarkAsRead")}
                      </button>
                    )}
                    <button 
                      onClick={() => handleDelete(notification.id)}
                      className="text-xs font-medium text-muted-foreground hover:text-destructive flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity"
                    >
                      <Trash2 className="h-3 w-3" />
                      {t("notifDelete")}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );

  if (isAdminOrStaff) {
    return <AdminLayout>{content}</AdminLayout>;
  }

  return (
    <PageShell>
      {content}
    </PageShell>
  );
}
