import { createContext, useContext, useState, ReactNode, useEffect } from "react";
import { useSettings } from "@/hooks/useSettings";
import { useAuth } from "./AuthContext";
import { apiFetch } from "@/services/api";


export type Language = "en" | "am" | "om";

interface LanguageOption {
  code: Language;
  label: string;
  nativeLabel: string;
}

export const languages: LanguageOption[] = [
  { code: "en", label: "English", nativeLabel: "English" },
  { code: "am", label: "Amharic", nativeLabel: "አማርኛ" },
  { code: "om", label: "Afaan Oromoo", nativeLabel: "Afaan Oromoo" },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    home: "Home",
    cars: "Cars",
    rentals: "Rentals",
    lottery: "Lottery",
    contact: "Contact",
    login: "Login",
    systemMaintenance: "System Maintenance",
    retry: "Retry",
    signUp: "Sign Up",
    carsForSale: "Cars for Sale",
    carsForRent: "Cars for Rent",

    // Hero
    heroTagline: "YOUR PREMIUM CAR DESTINATION",
    heroTitle: "Gech",
    heroTitleSub: "(ጌች)",
    heroDesc: "Discover, buy, rent, and win premium vehicles — all in one place. Ethiopia's finest car marketplace.",
    browseFleet: "Browse fleet",
    winACar: "Win a car",
    scrollToExplore: "Scroll to explore",
    browseCars: "Browse Cars",
    enterLottery: "Join Lottery",
    vehicles: "Vehicles",
    happyClients: "Happy Clients",
    lotteryDraws: "Lottery Draws",

    // Featured
    featured: "Featured",
    handpickedVehicles: "Handpicked Vehicles",
    viewAll: "View all",
    viewDetails: "View Details",
    sale: "Sale",
    rental: "Rental",

    // Services
    whatWeOffer: "What We Offer",
    threeWays: "Three Ways to Drive",
    buyACar: "Buy a Car",
    buyACarDesc: "Browse our curated inventory of premium vehicles with transparent pricing and detailed specs.",
    rentACar: "Rent a Car",
    rentACarDesc: "Flexible daily rentals with competitive rates. Pick up today, return when you're done.",
    carLottery: "Car Lottery",
    carLotteryDesc: "Select your lucky numbers, pay your ticket, and stand a chance to win incredible prizes.",

    // Lottery section (landing)
    howItWorks: "How It Works",
    winYourNextRide: "Win Your Next Ride",
    lotteryLandingDesc: "Our car lottery gives everyone a fair shot at winning premium vehicles. Here's how to enter.",
    pickYourNumbers: "Pick Your Numbers",
    pickNumbersDesc: "Choose from the available number grid — each number is yours exclusively.",
    confirmAndPay: "Confirm & Pay",
    confirmPayDesc: "Upload your payment receipt and wait for admin approval.",
    winBig: "Win Big",
    winBigDesc: "When the draw happens, matching numbers take home the grand prize.",
    enterTheLottery: "Enter the Lottery",

    // Trust
    verifiedVehicles: "Verified Vehicles",
    averageResponse: "Average Response",
    customerRating: "Customer Rating",

    // Lottery page
    lotteryTagline: "Gech (ጌች) Lottery",
    lotteryTitle: "Pick a Number, Win a Ride",
    lotteryDesc: "Our car lottery is your chance to drive home in a premium vehicle. Select your lucky numbers, confirm your ticket, and wait for the draw.",
    currentDraw: "CURRENT DRAW",
    grandPrize: "Grand Prize: To Be Announced",
    ticketPrice: "TICKET PRICE",
    numberRange: "Number Range",
    ticketsLeft: "Tickets Left",
    selectYourNumbers: "Select Your Numbers",
    step: "Step",
    chooseNumbers: "Choose Your Numbers",
    chooseNumbersDesc: "Browse the number grid and pick any available number. Each number can only be claimed once.",
    submitPayment: "Submit Payment",
    submitPaymentDesc: "Upload your payment receipt with a reference number. An admin will verify your payment.",
    waitForDraw: "Wait for the Draw",
    waitForDrawDesc: "Once all tickets are sold or the deadline passes, we draw the winning number live.",
    lotteryRules: "Lottery Rules",
    rule1: "Each participant may purchase up to 5 tickets per draw.",
    rule2: "Numbers are reserved upon payment approval — not upon selection.",
    rule3: "The draw date is announced once all tickets are sold or the deadline arrives.",
    rule4: "Winners must claim their prize within 30 days of the draw.",
    rule5: "All decisions by Gech (ጌች) administration are final.",

    // Lottery Select
    backToLottery: "Back to Lottery",
    pickUpTo5: "Pick up to 5 numbers. Gray numbers are already taken.",
    available: "Available",
    selected: "Selected",
    taken: "Taken",
    yourSelection: "Your Selection",
    noNumbersSelected: "No numbers selected yet.",
    tickets: "Tickets",
    priceEach: "Price each",
    total: "Total",
    confirmSelection: "Confirm Selection",
    numbersReserved: "Numbers Reserved!",
    youSelected: "You selected:",
    completePayment: "Complete your payment to confirm your participation.",
    goToPayment: "Go to Payment",

    // Cars pages
    inventory: "Inventory",
    searchVehicles: "Search vehicles...",
    filters: "Filters",
    brand: "Brand",
    all: "All",
    noVehiclesMatch: "No vehicles match your criteria.",
    clearFilters: "Clear Filters",
    forSale: "For Sale",
    forRent: "For Rent",
    sold: "Sold",
    rented: "Rented",
    unavailable: "Unavailable",
    contactToBuy: "Contact to Buy",
    noLongerAvailable: "No Longer Available",
    bookRental: "Book Rental",
    currentlyRented: "Currently Rented",
    paymentInfo: "Payment Info",
    backToSales: "Back to Sales",
    backToRentals: "Back to Rentals",
    vehicleNotFound: "Vehicle Not Found",
    backToListings: "Back to Listings",
    year: "Year",
    mileage: "Mileage",
    fuel: "Fuel",
    transmission: "Transmission",
    seats: "Seats",
    rentNow: "Rent Now",
    searchRentals: "Search rentals...",
    rentalsLabel: "Rentals",

    // Car Detail
    specifications: "Specifications",

    // Payment
    payment: "Payment",
    paymentPageDesc: "Upload your payment receipt to confirm your purchase or lottery entry.",
    submitPaymentReceipt: "Submit Payment Receipt",
    referenceNumber: "Reference Number",
    receiptImage: "Receipt Image",
    clickToUpload: "Click to upload receipt",
    uploadHint: "PNG, JPG up to 5MB",
    submitReceipt: "Submit Receipt",
    paymentHistory: "Payment History",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    homeLink: "Home",

    // Dashboard
    welcomeBack: "Welcome back",
    userAccountTier: "Premium Member",
    dashboardSubtitle: "Your command center for luxury acquisitions and active sweepstakes management.",
    activitySummary: "Here's a summary of your activity.",
    activeRentals: "Active Rentals",
    lotteryEntries: "Lottery Entries",
    pendingPayments: "Pending Payments",
    quickActions: "Quick Actions",
    browseCarsForSale: "Browse Cars for Sale",
    enterLotteryAction: "Enter Lottery",
    myProfile: "My Profile",
    activeEntries: "Active Entries",
    verifiedTickets: "Verified Tickets",
    awaitingVerification: "Awaiting Verification",
    savedVehicles: "Saved Assets",
    watchingStatus: "Watching Status",

    // Auth
    welcomeBackLogin: "Welcome Back",
    signInToAccount: "Sign in to your Gech (ጌች) account",
    demoAccounts: "Demo Accounts",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    signIn: "Sign In",
    noAccount: "Don't have an account?",
    createOne: "Create one",
    createAccount: "Create Account",
    joinGech: "Join Gech (ጌች) to buy, rent, or win",
    firstName: "First Name",
    lastName: "Last Name",
    phone: "Phone",
    haveAccount: "Already have an account?",
    signInLink: "Sign in",
    atLeast8: "At least 8 characters",
    containsNumber: "Contains a number",
    containsUppercase: "Contains uppercase",

    // Footer
    footerDesc: "Your trusted partner for car sales, rentals, and exciting lottery draws. Premium vehicles, transparent pricing.",
    quickLinks: "Quick Links",
    aboutUs: "About Us",
    account: "Account",
    logIn: "Log In",
    register: "Register",
    dashboard: "Dashboard",
    contactFooter: "Contact",
    allRightsReserved: "All rights reserved.",

    // Contact page
    contactTagline: "Get in Touch",
    contactTitle: "Contact Us",
    contactDesc: "Have questions about our cars, rentals, or lottery? We'd love to hear from you.",
    phoneLabel: "Phone",
    phoneTap: "Tap to call on mobile",
    telegramLabel: "Telegram",
    telegramTap: "Opens Telegram app",
    emailLabel: "Email",
    addressLabel: "Address",
    addressValue: "Jemo3 beside Taf gas station",
    hoursLabel: "Business Hours",
    hoursValue: "Mon–Sat: 8:00 AM – 6:00 PM",
    savedCars: "Saved Cars",
    noSavedCars: "You haven't saved any cars yet.",
    signInToSave: "Please sign in to save cars.",

    // Admin
    adminDashboard: "Admin Dashboard",
    management: "Management",
    lotteryOps: "Lottery Ops",
    adminCars: "Cars Management",
    adminUsers: "User Management",
    adminLottery: "Lottery Settings",
    lotteryPayments: "Lottery Payments",
    generateNumbers: "Generate Numbers",
    participants: "Participants",
    adminSettings: "System Settings",
    totalVehicles: "Total Vehicles",
    estRevenue: "Est. Revenue",
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    goodEvening: "Good evening",
    lotteryPortal: "Lottery Portal",
    adminCommandCenter: "Admin Command Center",
    overviewMetrics: "Overview Metrics",
    live: "Live",
    review: "Review",
    totalLabel: "Total",
    est: "Est",

    // Admin Common
    cancel: "Cancel",
    actions: "Actions",
    confirmDeletion: "Confirm Deletion",
    delete: "Delete",

    // Admin Cars
    carManagement: "Car Management",
    addEditRemoveVehicles: "Add, edit, or remove vehicles from your inventory",
    addVehicle: "Add Vehicle",
    searchByName: "Search by name...",
    vehicleDetails: "Vehicle Details",
    priceBirr: "Price (Birr)",
    noVehiclesInventory: "No vehicles in inventory",
    editVehicleDetails: "Edit Vehicle Details",
    addNewVehicle: "Add New Vehicle",
    make: "Make",
    model: "Model",
    dealType: "Deal Type",
    availability: "Availability",
    vehicleShowcaseImage: "Vehicle Showcase Image",
    clickToUploadImage: "Click to upload image",
    vehicleDescription: "Vehicle Description",
    updateVehicle: "Update Vehicle",
    areYouSureDeleteCar: "Are you sure you want to remove this vehicle from your inventory? This action is permanent.",
    deleteCar: "Delete Car",

    // Admin Users
    userManagement: "User Management",
    manageSystemAccess: "Manage system access and roles",
    searchUsersPrompt: "Search users by name or email...",
    userDetails: "User Details",
    loadingUserDatabase: "Loading user database...",
    noMatchingUsers: "No matching users found",
    suspendUser: "Suspend User",
    activateUser: "Activate User",
    deleteAccount: "Delete Account",
    areYouSureDeleteUser: "Are you sure you want to permanently delete this user? This action cannot be undone.",
    suspensionReason: "Suspension Reason",
    confirmSuspension: "Confirm Suspension",
    suspensionPrompt: "Please provide a reason for suspending this account. The user will be immediately blocked from all access.",
    adminRefresh: "Refresh",
    adminAddStaff: "Add Staff",
    adminProvisionStaff: "Provision Staff Account",
    adminStaffDescription: "Generate a secure login exclusively for the lottery staff role. Regular users cannot request this access.",
    adminWorkEmail: "Work Email",
    adminInitialPassword: "Initial Password",
    adminCreateStaff: "Create Staff",
    adminTotalUsers: "Total Users",
    adminActiveUsers: "Active",
    adminSuspendedUsers: "Suspended",
    adminStaffMembers: "Staff members",
    adminConfirmDeletion: "Confirm Deletion",
    adminStaffCreated: "Staff Created",
    adminStaffSuccess: "The new lottery staff account was generated successfully.",
    adminValidationError: "Validation Error",
    adminAllFieldsRequired: "All fields are required.",
    adminPasswordLength: "Password must be at least 6 characters.",
    adminGenerationFailed: "Generation failed",
    adminCouldNotCreateStaff: "Could not create staff account.",
    adminAccountActivated: "Account Activated",
    adminAccountActivatedDesc: "'s account is now active.",
    adminUserSuspended: "User Suspended",
    adminAccountRevoked: "Account access has been revoked.",
    adminUserDeleted: "User Deleted",
    adminAccountRemoved: "Account removed successfully.",

    // Admin Lottery
    lotteryManagement: "Lottery Management",
    activeDraw: "Active Draw",
    lotteryControl: "Lottery Control",
    activePrize: "Active Prize",
    range: "Range",
    stopLottery: "Stop Lottery",
    numberRangeLabel: "Number Range",
    ticketPriceCalc: "Ticket Price",
    initializeNewDraw: "Initialize New Draw",
    prepareForDraw: "Prepare for the Draw",
    drawWinnerDesc: "Once the lottery is closed and all payments are verified, you can select a random winner from the confirmed participants.",
    drawTheWinner: "Draw the Winner",
    lotteryConfirmed: "Confirmed",
    lotteryPending: "Pending",
    lotteryFree: "Free",

    // Admin Settings - General
    generalSettings: "General System Settings",
    platformName: "Platform Name",
    logo: "Logo",
    uploadLogo: "Upload Logo",
    defaultCurrency: "Default Currency",
    defaultLanguage: "Default Language",
    timezone: "Timezone",
    dateFormat: "Date Format",
    contactInformation: "Contact Information",
    contactEmail: "Contact Email",
    contactPhone: "Contact Phone",
    physicalAddress: "Physical Address",
    saveGeneralSettings: "Save General Settings",

    // Admin Settings - Security
    securityAccess: "Security & Access",
    enableRegistration: "Enable User Registration",
    registrationDesc: "Allow new users to create accounts",
    minPasswordLength: "Minimum Password Length",
    sessionTimeout: "Session Timeout (minutes)",
    requireUppercase: "Require Uppercase Characters",
    uppercaseDesc: "Password must contain at least one uppercase letter",
    requireNumbers: "Require Numbers",
    numbersDesc: "Password must contain at least one digit",
    allowMultiLogin: "Allow Multi-Login",
    multiLoginDesc: "Allow same account to be logged in on multiple devices",
    saveSecuritySettings: "Save Security Settings",

    // Admin Settings - Lottery
    lotteryModule: "Lottery Module",
    lotteryModuleDesc: "When disabled, users cannot view lottery, buy tickets, or upload payments.",
    lotteryConfiguration: "Lottery Configuration",
    drawFrequency: "Draw Frequency",
    autoCloseLabel: "Auto-Close Before Draw (min)",
    staffPermissions: "Lottery Staff Permissions",
    paymentVerificationPerm: "Payment Verification",
    numberGenPerm: "Number Generation",
    adminOverridePerm: "Admin Override",
    saveLotterySettings: "Save Lottery Settings",

    // Admin Settings - Operational
    operationalControls: "Operational Controls",
    operationalDesc: "Master switches for emergency shutdown or audits.",
    enableEntirePlatform: "Enable Entire Platform",
    platformShutdownDesc: "Turning off shuts down the entire platform for all users",
    maintenanceMessageLabel: "Maintenance Mode Message",
    saveOperationalSettings: "Save Operational Settings",

    // Admin Settings - Logs
    systemLogs: "System Logs",
    allActions: "All Actions",
    adminOnly: "Admin Only",
    staffOnly: "Staff Only",
    exportCSV: "Export CSV",
    noLogsFound: "No logs found.",

    // Admin Settings - Notifications
    notificationSettings: "Notification Settings",
    emailNotifications: "Email Notifications",
    smsNotifications: "SMS Notifications",
    largePaymentAlerts: "Large Payment Alerts",
    suspiciousActivityAlerts: "Suspicious Activity Alerts",
    saveNotificationSettings: "Save Notification Settings",

    // Admin Settings - Backup
    backupRecovery: "Backup & Recovery",
    backupFrequency: "Backup Frequency",
    manualBackup: "Trigger Manual Backup",
    remoteSnapshots: "Remote SQL Snapshots",
    saveBackupSettings: "Save Backup Settings",

    // Dashboard & Sidebar
    navGenerateNumbers: "Generate Numbers",
    navLotteryPayments: "Lottery Payments",
    navNumberBoard: "Number Board",
    navParticipants: "Participants",
    navUsers: "Users",
    navManagementPortal: "Management Portal",
    navCoreManagement: "Core Management",
    navLotteryOperations: "Lottery Operations",
    navTerminateSession: "Terminate Session",
    navEngineHealthy: "Engine Healthy",
    navStaffPortal: "Staff Portal",
    navGlobalAdmin: "Global Admin",
    navSystemId: "System ID",
    navDashboard: "Dashboard",

    // Notifications Page
    notifMarkAllAsRead: "Mark all as read",
    notifLoading: "Loading notifications...",
    notifNoNotificationsYet: "No notifications yet",
    notifWhenUpdatesAppear: "When you have updates, they'll appear here.",
    notifMarkAsRead: "Mark as read",
    notifDelete: "Delete",

    // Admin Dashboard
    lotteryOpsPortal: "Lottery Ops Portal",
    dashAdminCommandCenter: "Admin Command Center",
    platformRunningOpt: "Your platform is running at optimal capacity. Check out the latest activity reports below.",
    systemSecure: "System Secure",
    liveIntelligence: "Live Intelligence",
    realTimeData: "Real-time Data",
    actionRequired: "Action Required",
    fourThisWeek: "+4 this week",
    dashEstRevenue: "Est. Revenue",
    etbTotal: "ETB Total",
    recentEvents: "Recent Events",
    viewFullAudit: "View Full Audit",
    gatheringLogs: "Gathering Activity logs...",
    newLotteryCreated: "New Lottery Created",
    securityPolicyUpdated: "Security Policy Updated",
    paymentManualOverride: "Payment Manual Override",
    adminDiagnosticsSweep: "Admin performed global sweep of system diagnostics and verified pending tickets.",
    operations: "Operations",
    fastLotterySetup: "Fast Lottery Setup",
    initializationTools: "Initialization Tools",
    newDraw: "New Draw",

    // Admin Lottery Subpages
    alGenerateNumbers: "Generate Numbers",
    alSetRangeAndPrize: "Set a number range and prize — the system generates all tickets instantly.",
    alMainPrize: "Main Prize",
    alTicketPriceSettings: "Ticket Price via Settings",
    alPrizeExample: "e.g. 2024 Toyota Camry",
    alInitializing: "Initializing...",
    alDrawingWinner: "Drawing Winner...",
    alRequiresConfirmedTicket: "Requires at least 1 confirmed ticket payment to draw.",
    alOneLuckyWinner: "One lucky ticket holder will win! Ensure all payments are verified before drawing.",
    
    lpLotteryParticipants: "Lottery Participants",
    lpActiveDraw: "Active Draw:",
    lpSearchPlaceholder: "Search by name or ticket #…",
    lpTotalParticipants: "Total Participants",
    lpConfirmedTickets: "Confirmed Tickets",
    lpPendingReview: "Pending Review",
    lpNoParticipantsMatching: "No participants matching your search.",
    lpNoVerifiedParticipants: "No verified participants found yet.",
    lpParticipantsAppearOnce: "Participants appear once a payment has been submitted.",
    lpParticipant: "Participant",
    lpTicketNumbers: "Ticket Numbers",
    lpCount: "Count",
    lpJoined: "Joined",
    lpShowingParticipants: "Showing",
    lpOf: "of",
    lpClearSearch: "Clear search",
    
    payLotteryPayments: "Lottery Payments",
    payReviewVerify: "Review and verify user payment receipts for lottery tickets.",
    payRefresh: "Refresh",
    payAll: "All",
    payTotal: "Total",
    payNoPaymentsFilter: "No payments matching your filter.",
    payNoLotteryPayments: "No lottery payment records found.",
    payPaymentsAppearOnce: "Payments appear once users submit their receipts.",
    payUser: "User",
    payMethod: "Method",
    payTicket: "Ticket",
    payReceipt: "Receipt",
    payStatus: "Status",
    payActions: "Actions",
    payApprove: "Approve",
    payReject: "Reject",
    payView: "View",

    glNumberBoard: "Number Board",
    glLiveView: "Live view of all ticket numbers and their current status for the active draw.",
    glActiveDrawText: "Active draw",
    glRangeText: "Range",
    glNumbersGeneratedAuto: "Numbers are generated automatically when Admin creates a new lottery.",
    glTotalNumbers: "Total Numbers",
    glNoActiveLottery: "No active lottery found.",
    glGoToLotteryManagement: "Go to Lottery Management to create and start a new draw.",
    glNoNumbersMatch: "No numbers match the current filter.",

    // Lottery User Pages
    l_syncingDraw: "Syncing with Live Draw...",
    l_platformVerified: "Platform Verified",
    l_premiumVehicleExp: "Premium Vehicle Experience",
    l_secureBlockchain: "Secure Blockchain Selection",
    l_activeNow: "Active Now",
    l_noActiveSweepstakes: "No Active Sweepstakes",
    l_preparingNextDraw: "We're currently preparing our next grand draw. Please check back soon.",
    l_numbersReserved: "Numbers Reserved",
    l_reservedSuccess: "You've successfully reserved numbers:",
    l_finalizeEntry: "Finalize your entry by submitting your receipt.",
    l_backToLottery: "Back to Lottery",
    l_selectionStep: "Selection Step",
    l_pickLuckyPath: "Pick your lucky path",
    l_syncingBoard: "Syncing Number Board...",
    l_restrictedAccess: "Restricted Access",
    l_managementRestriction: "Management accounts are not permitted to participate.",
    l_boardOffline: "Board Offline",

    // Profile Page
    profVerifiedProfile: "Verified Profile",
    profMemberSince: "Platform Member since 2026",
    profEntries: "Entries",
    profRentals: "Rentals",
    profSave: "Save",
    profEdit: "Edit",
    profSecurityIdentity: "Security & Identity",
    profProfileConfiguration: "Profile Configuration",
    profFirstName: "First Name",
    profLastName: "Last Name",
    profEmailTerminal: "Email Terminal",
    profContactConnection: "Contact Connection",
    profSyncChanges: "Sync Changes",
    profStatusLevel: "Status Level",
    profCoreContributor: "Core Contributor",
    profProgressToPlatinum: "Progress to Platinum",
    profRecentActivity: "RECENT DRAWING STREAM",
    profSynchronizedLedger: "FULL REGISTRY",
    profFinancialHistory: "Financial & Token History",
    profRequestingArchives: "Requesting Archives...",
    profNoActiveHistory: "No Active History Found",
    profStartJourney: "Start your journey by exploring active lotteries.",
    profExploreDraws: "Explore Draws",
    profEndOfHistory: "End of History Stream",
    profRequestAudit: "Request Full Audit Data",
    profFleetAccess: "Fleet Access",
    profActiveRentalContracts: "Total active rental contracts:",
    profManageFleet: "Manage Fleet",
    profPendingEntry: "Pending",
    profConfirmedEntry: "Confirmed Entry",
    profRejectedEntry: "Rejected",
    profVerifyingReceipt: "Verifying Receipt",
    profAwaitingPayment: "Awaiting Payment",
    profWinner: "WINNER",
    profStandardEntry: "LOTTERY PARTICIPATION ENTRY",
    logout: "Logged Out",
    logoutSuccess: "You have been successfully logged out.",
    profileSynchronized: "Your changes have been saved successfully.",
    navTickets: "My Tickets",
    notifications: "Notifications",

    // Auth Extended
    authEncryptedAccess: "Encrypted Access Point",
    authPremiumTitle: "YOUR PREMIUM",
    authJourneyStarts: "JOURNEY STARTS HERE.",
    authLoginDesc: "Log in to access your curated dashboard, participate in elite sweepstakes, and manage your luxury vehicle interests.",
    authVettedAssets: "Vetted Assets",
    authFairPlay: "Fair Play",
    authAuthenticatedAccess: "Authenticated Access",
    authEstablishingSession: "ESTABLISHING SESSION...",
    authWelcomeBackMsg: "Welcome back",
    authSecureSession: "Secure session established.",
    authAccessDenied: "Access Denied",
    authNetworkError: "Network Error",
    authConnectionFailed: "Standard secure connection failed.",
    authInitializationIdentity: "INITIALIZING IDENTITY...",
    authSecureNodeInitialization: "Secure Node Initialization",
    authJoinEliteNetwork: "JOIN THE ELITE NETWORK.",
    authRegisterDesc: "Create your account to unlock exclusive access to high-stakes draws, premium rentals, and our vetted luxury vehicle sales marketplace.",
    authTransparentDraw: "Transparent Draw Protocol",
    authVerifiedAssetNetwork: "Verified Asset Network",
    authSeamlessAssetManagement: "Seamless Asset Management",
    authCreateIdentity: "Create Identity",
    authAccountInitialized: "Account Initialized",
    authIdentityVerified: "Identity verified. You can now establish a session.",
    authRegistrationBlocked: "Registration Blocked",
    authCredentialConflict: "Credential conflict detected.",
    authConnectionError: "Connection Error",
    authSecureNodeRegistration: "Secure node registration failed.",

    // Payment Extended
    paySecureCheckout: "Secure Checkout",
    payRestrictedAccess: "Restricted Access",
    payManagementRestriction: "Management accounts are not permitted to submit payments or participate in lottery draws to maintain system integrity.",
    paySelectionReservation: "Select Reservation",
    payWhichReservation: "Which reservation are you paying for?",
    payNoReservedFound: "No Reserved Numbers Found",
    payPickConfirmNumbers: "You must pick and confirm your numbers on the lottery board before paying.",
    payGoToBoard: "Go to Number Board",
    payAmountDue: "Amount Due",
    payGateway: "Payment Gateway",
    payValidationMedia: "Validation Media",
    payReplaceImage: "Replace Image",
    payStreamingData: "STREAMING DATA...",
    payValidatingSession: "VALIDATING SESSION...",
    payOfficialAccount: "Official Account",
    payTransferInstructions: "Please transfer the exact amount for your selected tickets. Double check the account number before sending. High-quality screenshots are required for verification.",
    payCBE: "Commercial Bank (CBE)",
    payTelebirrWallet: "Telebirr Wallet",
    payDriveHubAccount: "Drive Hub Lottery Account",
    payAdminTerminal: "Admin Payment Terminal",
    payRecentActivity: "Recent Activity",
    payFetchingLedger: "Fetching Ledger...",
    payNoTransactionHistory: "No Transaction History",
    payUnderReview: "Under Review",
    payVerifyingReceipt: "Verifying Receipt",
    payAwaitingPayment: "Awaiting Payment",
    payPaymentRejected: "Payment Rejected",
    payTicketEntry: "Ticket Entry",

    appSuffix: "Car Sales & Rentals",

    // Admin Extended
    adminSystemCore: "system core",
    adminSettingsDesc: "Fine-tune your platform experience and operational parameters.",
    adminGeneralDesc: "Base configuration for your platform presence.",
    adminSecurityDesc: "Enforce password policies and session behavior.",
    adminLotteryDesc: "Core mechanics and pricing for your car lotteries.",
    adminOperationalDesc: "High-level platform switches and maintenance mode.",
    adminNotificationsDesc: "Control how and when admins and users are alerted.",
    adminBackupDesc: "Secure your data with cloud snapshots and manual dumps.",
    adminLogsDesc: "Audit trail of critical administrative and staff actions.",
    adminStartingBackup: "Starting Backup",
    adminTriggeringBackup: "Triggering manual database backup...",
    adminBackupFinalized: "Backup Finalized",
    adminBackupSuccess: "Remote SQL dump created successfully.",
    adminMaxTicketsPerUser: "Max Tickets/User",
    adminManualStaffTriggered: "Manual (Staff Triggered)",
    adminWeeklyAuto: "Weekly Automatic",
    adminDailyAuto: "Daily Automatic",
    adminLotteryEngine: "Lottery Engine",
    adminToggleTicketing: "Toggle ticketing and draws",
    adminMaintenancePlaceholder: "We're currently performing scheduled maintenance. Please check back later.",
    adminEmailEngine: "Email Engine",
    adminSmsGateway: "SMS Gateway",
    adminSecurityAlerts: "Security/Suspicious Alerts",
    adminAutoSnapshotSchedule: "Auto-snapshot schedule",
    adminRollbackSystem: "Rollback System",
    adminEverywhere: "Everywhere",
    adminNoLogsMatching: "No logs matching your current filters.",
    role: "Role",
    admin: "Admin",
    lotteryStaff: "Lottery Staff",
    user: "User",
    suspended: "Suspended",
    active: "Active",
    processing: "Processing...",
    generating: "Generating...",
    profPremiumUser: "Premium User",
    profUserPlaceholder: "User",
    profEmailPlaceholder: "user@email.com",
    profPhonePlaceholder: "+251 900 000 000",
    adminConfirmSuspensionDesc: "Are you sure you want to suspend this user?",
    adminSuspensionReasonPlaceholder: "e.g. Violation of Terms of Service...",
  },
  am: {
    // Nav
    home: "መነሻ",
    cars: "መኪናዎች",
    rentals: "ኪራይ",
    lottery: "ሎተሪ",
    contact: "ያግኙን",
    login: "ግባ",
    systemMaintenance: "ስርዓቱ በጥገና ላይ ነው",
    retry: "እንደገና ይሞክሩ",
    signUp: "ተመዝገብ",
    carsForSale: "ለሽያጭ መኪናዎች",
    carsForRent: "ለኪራይ መኪናዎች",

    // Hero
    heroTagline: "የፕሪሚየም መኪናዎች መድረሻ",
    heroTitle: "ጌች",
    heroTitleSub: "",
    heroDesc: "ፕሪሚየም ተሽከርካሪዎችን በአንድ ቦታ ይለዩ፣ ይግዙ፣ ይከራዩ እና ያሸንፉ። የኢትዮጵያ ምርጥ የመኪና ገበያ።",
    browseFleet: "የዝርዝር መመልከቻ",
    winACar: "መኪና ያሸንፉ",
    scrollToExplore: "ለማሰስ ወደ ታች ይውረዱ",
    browseCars: "መኪናዎችን ይመልከቱ",
    enterLottery: "ሎተሪ ይግቡ",
    vehicles: "ተሽከርካሪዎች",
    happyClients: "ደስተኛ ደንበኞች",
    lotteryDraws: "የሎተሪ ዕጣዎች",

    // Featured
    featured: "ተለይተው የቀረቡ",
    handpickedVehicles: "በጥንቃቄ የተመረጡ ተሽከርካሪዎች",
    viewAll: "ሁሉንም ይመልከቱ",
    viewDetails: "ዝርዝር ይመልከቱ",
    sale: "ሽያጭ",
    rental: "ኪራይ",

    // Services
    whatWeOffer: "አገልግሎቶቻችን",
    threeWays: "ሶስት የመንዳት መንገዶች",
    buyACar: "መኪና ይግዙ",
    buyACarDesc: "ፕሪሚየም ተሽከርካሪዎችን ግልጽ ዋጋና ዝርዝር መግለጫ ጋር ይመልከቱ።",
    rentACar: "መኪና ይከራዩ",
    rentACarDesc: "ተወዳዳሪ ዋጋ ያላቸው ተለዋዋጭ ዕለታዊ ኪራዮች። ዛሬ ይውሰዱ፣ ሲጨርሱ ይመልሱ።",
    carLottery: "የመኪና ሎተሪ",
    carLotteryDesc: "ዕድለኛ ቁጥሮችዎን ይምረጡ፣ ትኬትዎን ይክፈሉ፣ አስደናቂ ሽልማቶችን ለማሸነፍ ዕድል ያግኙ።",

    // Lottery section (landing)
    howItWorks: "እንዴት ይሠራል",
    winYourNextRide: "ቀጣዩን መኪናዎን ያሸንፉ",
    lotteryLandingDesc: "የመኪና ሎተሪያችን ሁሉንም ሰው ፕሪሚየም ተሽከርካሪ ለማሸነፍ ፍትሃዊ ዕድል ይሰጣል።",
    pickYourNumbers: "ቁጥሮችዎን ይምረጡ",
    pickNumbersDesc: "ከሚገኙ ቁጥሮች ይምረጡ — እያንዳንዱ ቁጥር የእርስዎ ብቻ ነው።",
    confirmAndPay: "ያረጋግጡ እና ይክፈሉ",
    confirmPayDesc: "የክፍያ ደረሰኝዎን ያስገቡ እና የአስተዳዳሪ ማጽደቅ ይጠብቁ።",
    winBig: "ትልቅ ያሸንፉ",
    winBigDesc: "ዕጣው ሲወጣ ተመሳሳይ ቁጥሮች ዋናውን ሽልማት ይወስዳሉ።",
    enterTheLottery: "ሎተሪ ይግቡ",

    // Trust
    verifiedVehicles: "የተረጋገጡ ተሽከርካሪዎች",
    averageResponse: "አማካይ ምላሽ",
    customerRating: "የደንበኛ ደረጃ",

    // Lottery page
    lotteryTagline: "ጌች ሎተሪ",
    lotteryTitle: "ቁጥር ይምረጡ፣ መኪና ያሸንፉ",
    lotteryDesc: "የመኪና ሎተሪያችን ፕሪሚየም ተሽከርካሪ ወደ ቤት ለመንዳት እድል ነው። ዕድለኛ ቁጥሮችዎን ይምረጡ፣ ትኬትዎን ያረጋግጡ እና ዕጣውን ይጠብቁ።",
    currentDraw: "የአሁኑ ዕጣ",
    grandPrize: "ዋና ሽልማት: ወደፊት የሚገለፅ",
    ticketPrice: "የቲኬት ዋጋ",
    numberRange: "የቁጥር ክልል",
    ticketsLeft: "የቀሩ ትኬቶች",
    selectYourNumbers: "ቁጥሮችዎን ይምረጡ",
    step: "ደረጃ",
    chooseNumbers: "ቁጥሮችዎን ይምረጡ",
    chooseNumbersDesc: "የቁጥር ፍርግርግ ውስጥ ያስሱ እና ማንኛውንም ያልተያዘ ቁጥር ይምረጡ።",
    submitPayment: "ክፍያ ያስገቡ",
    submitPaymentDesc: "የክፍያ ደረሰኝዎን ከማጣቀሻ ቁጥር ጋር ያስገቡ። አስተዳዳሪ ክፍያዎን ያረጋግጣል።",
    waitForDraw: "ዕጣውን ይጠብቁ",
    waitForDrawDesc: "ሁሉም ትኬቶች ከተሸጡ ወይም የጊዜ ገደቡ ካለፈ በኋላ ዕጣውን በቀጥታ እንጫናለን።",
    lotteryRules: "የሎተሪ ደንቦች",
    rule1: "እያንዳንዱ ተሳታፊ በአንድ ዕጣ እስከ 5 ትኬቶች መግዛት ይችላል።",
    rule2: "ቁጥሮች የሚያዙት ክፍያ ሲፀድቅ ነው — ሲመርጡ አይደለም።",
    rule3: "የዕጣ ቀን ሁሉም ትኬቶች ሲሸጡ ወይም የጊዜ ገደቡ ሲደርስ ይገለጻል።",
    rule4: "አሸናፊዎች ሽልማታቸውን ከዕጣው በ30 ቀናት ውስጥ መጠየቅ አለባቸው።",
    rule5: "ሁሉም ውሳኔዎች በጌች አስተዳደር የመጨረሻ ናቸው።",

    // Lottery Select
    backToLottery: "ወደ ሎተሪ ተመለስ",
    pickUpTo5: "እስከ 5 ቁጥሮች ይምረጡ። ግራጫ ቁጥሮች ቀድሞ ተይዘዋል።",
    available: "ያልተያዘ",
    selected: "የተመረጠ",
    taken: "የተያዘ",
    yourSelection: "ምርጫዎ",
    noNumbersSelected: "ገና ቁጥር አልተመረጠም።",
    tickets: "ትኬቶች",
    priceEach: "የእያንዳንዱ ዋጋ",
    total: "ጠቅላላ",
    confirmSelection: "ምርጫ ያረጋግጡ",
    numbersReserved: "ቁጥሮች ተይዘዋል!",
    youSelected: "የመረጡት:",
    completePayment: "ተሳትፎዎን ለማረጋገጥ ክፍያዎን ያጠናቅቁ።",
    goToPayment: "ወደ ክፍያ ይሂዱ",

    // Cars pages
    inventory: "ዝርዝር",
    searchVehicles: "ተሽከርካሪዎችን ይፈልጉ...",
    filters: "ማጣሪያዎች",
    brand: "ብራንድ",
    all: "ሁሉም",
    noVehiclesMatch: "ከመስፈርትዎ ጋር የሚመሳሰል ተሽከርካሪ የለም።",
    clearFilters: "ማጣሪያዎችን ያጽዱ",
    forSale: "ለሽያጭ",
    forRent: "ለኪራይ",
    sold: "ተሽጧል",
    rented: "ተከራይቷል",
    unavailable: "የማይገኝ",
    contactToBuy: "ለመግዛት ያግኙን",
    noLongerAvailable: "ከእንግዲህ አይገኝም",
    bookRental: "ኪራይ ያስይዙ",
    currentlyRented: "በአሁኑ ጊዜ ተከራይቷል",
    paymentInfo: "የክፍያ መረጃ",
    backToSales: "ወደ ሽያጭ ተመለስ",
    backToRentals: "ወደ ኪራይ ተመለስ",
    vehicleNotFound: "ተሽከርካሪ አልተገኘም",
    backToListings: "ወደ ዝርዝሮች ተመለስ",
    year: "ዓመት",
    mileage: "ኪ.ሜ.",
    fuel: "ነዳጅ",
    transmission: "ስርጭት",
    seats: "መቀመጫዎች",
    rentNow: "አሁን ይከራዩ",
    searchRentals: "ኪራይ ይፈልጉ...",
    rentalsLabel: "ኪራዮች",

    // Car Detail
    specifications: "ዝርዝር መግለጫዎች",

    // Payment
    payment: "ክፍያ",
    paymentPageDesc: "ግዢዎን ወይም የሎተሪ ተሳትፎዎን ለማረጋገጥ የክፍያ ደረሰኝዎን ያስገቡ።",
    submitPaymentReceipt: "የክፍያ ደረሰኝ ያስገቡ",
    referenceNumber: "ማጣቀሻ ቁጥር",
    receiptImage: "የደረሰኝ ምስል",
    clickToUpload: "ደረሰኝ ለማስገባት ይጫኑ",
    uploadHint: "PNG, JPG እስከ 5MB",
    submitReceipt: "ደረሰኝ ያስገቡ",
    paymentHistory: "የክፍያ ታሪክ",
    pending: "በመጠባበቅ ላይ",
    approved: "ጸድቋል",
    rejected: "ተቀባይነት አላገኘም",
    homeLink: "መነሻ",

    // Dashboard
    welcomeBack: "እንኳን ደህና መጡ",
    userAccountTier: "ፕሪሚየም አባል",
    dashboardSubtitle: "ለቅንጦት ግዢዎችዎ እና ለንቁ የሎተሪ ተሳትፎዎችዎ ማዕከላዊ መቆጣጠሪያ።",
    activitySummary: "የእንቅስቃሴዎ ማጠቃለያ እዚህ አለ።",
    activeRentals: "ንቁ ኪራዮች",
    lotteryEntries: "የሎተሪ ተሳትፎዎች",
    pendingPayments: "በመጠባበቅ ያሉ ክፍያዎች",
    quickActions: "ፈጣን ድርጊቶች",
    browseCarsForSale: "ለሽያጭ መኪናዎችን ይመልከቱ",
    enterLotteryAction: "ሎተሪ ይግቡ",
    myProfile: "መገለጫዬ",
    activeEntries: "ንቁ ተሳትፎዎች",
    verifiedTickets: "የተረጋገጡ ትኬቶች",
    awaitingVerification: "በመጠባበቅ ላይ",
    savedVehicles: "የተቀመጡ ተሽከርካሪዎች",
    watchingStatus: "ክትትል ላይ",

    // Auth
    welcomeBackLogin: "እንኳን ደና ተመለሱ",
    signInToAccount: "ወደ ጌች መለያዎ ይግቡ",
    demoAccounts: "የማሳያ መለያዎች",
    email: "ኢሜይል",
    password: "የይለፍ ቃል",
    forgotPassword: "የይለፍ ቃል ረሱ?",
    signIn: "ግባ",
    noAccount: "መለያ የለዎትም?",
    createOne: "ይፍጠሩ",
    createAccount: "መለያ ይፍጠሩ",
    joinGech: "ለመግዛት፣ ለመከራየት ወይም ለማሸነፍ ጌችን ይቀላቀሉ",
    firstName: "ስም",
    lastName: "የአባት ስም",
    phone: "ስልክ",
    haveAccount: "ቀድሞ መለያ አለዎት?",
    signInLink: "ይግቡ",
    atLeast8: "ቢያንስ 8 ቁምፊዎች",
    containsNumber: "ቁጥር ይዟል",
    containsUppercase: "ትልቅ ፊደል ይዟል",

    // Footer
    footerDesc: "ለመኪና ሽያጭ፣ ኪራይ እና አስደሳች የሎተሪ ዕጣዎች ታማኝ አጋርዎ።",
    quickLinks: "ፈጣን ማገናኛዎች",
    aboutUs: "ስለ እኛ",
    account: "መለያ",
    logIn: "ግባ",
    register: "ተመዝገብ",
    dashboard: "ዳሽቦርድ",
    contactFooter: "ያግኙን",
    allRightsReserved: "ሁሉም መብቶች የተጠበቁ ናቸው።",

    // Contact page
    contactTagline: "ያግኙን",
    contactTitle: "እኛን ያነጋግሩ",
    contactDesc: "ስለ መኪናዎቻችን፣ ኪራዮች ወይም ሎተሪ ጥያቄ አለዎት? ከእርስዎ ለመስማት ደስ ይለናል።",
    phoneLabel: "ስልክ",
    phoneTap: "በሞባይል ላይ ለመደወል ይንኩ",
    telegramLabel: "ቴሌግራም",
    telegramTap: "የቴሌግራም መተግበሪያ ይከፈታል",
    emailLabel: "ኢሜይል",
    addressLabel: "አድራሻ",
    addressValue: "ጀሞ3 ጣፍ ነዳጅ መሸጫ አጠገብ",
    hoursLabel: "የስራ ሰዓት",
    hoursValue: "ሰኞ–ቅዳሜ: 8:00 ጠ. – 6:00 ከሰ.",
    savedCars: "የተቀመጡ መኪናዎች",
    noSavedCars: "እስካሁን ምንም የተቀመጡ መኪናዎች የሉም።",
    signInToSave: "መኪናዎችን ለማስቀመጥ እባክዎ ይግቡ።",

    // Admin
    adminDashboard: "አስተዳዳሪ ዳሽቦርድ",
    management: "አስተዳደር",
    lotteryOps: "የሎተሪ ስራዎች",
    adminCars: "የመኪና አስተዳደር",
    adminUsers: "የተጠቃሚዎች አስተዳደር",
    adminLottery: "የሎተሪ ቅንጅቶች",
    lotteryPayments: "የሎተሪ ክፍያዎች",
    generateNumbers: "ቁጥሮችን ማመንጨት",
    participants: "ተሳታፊዎች",
    adminSettings: "የስርዓት ቅንጅቶች",
    totalVehicles: "ጠቅላላ ተሽከርካሪዎች",
    estRevenue: "ግምታዊ ገቢ",
    goodMorning: "እንደምን አደሩ",
    goodAfternoon: "እንደምን ዋሉ",
    goodEvening: "እንደምን አመሹ",


    // Admin Common
    cancel: "ሰርዝ",
    actions: "እርምጃዎች",
    confirmDeletion: "መሰረዙን ያረጋግጡ",
    delete: "ሰርዝ",

    // Admin Cars
    carManagement: "የመኪና አስተዳደር",
    addEditRemoveVehicles: "ተሽከርካሪዎችን ከዝርዝርዎ ውስጥ ይጨምሩ፣ ያርሙ ወይም ያስወግዱ",
    addVehicle: "መኪና ጨምር",
    searchByName: "በስም ፈልግ...",
    vehicleDetails: "የተሽከርካሪ ዝርዝሮች",
    priceBirr: "ዋጋ (ብር)",
    noVehiclesInventory: "በዝርዝሩ ውስጥ ምንም ተሽከርካሪ የለም",
    editVehicleDetails: "የተሽከርካሪ ዝርዝሮችን ያርሙ",
    addNewVehicle: "አዲስ ተሽከርካሪ ጨምር",
    make: "ብራንድ",
    model: "ሞዴል",
    dealType: "የስምምነት ዓይነት",
    availability: "ዝግጁነት",
    vehicleShowcaseImage: "የተሽከርካሪ ማሳያ ምስል",
    clickToUploadImage: "ምስል ለመጫን እዚህ ይጫኑ",
    vehicleDescription: "የተሽከርካሪ መግለጫ",
    updateVehicle: "ተሽከርካሪውን አዘምን",
    areYouSureDeleteCar: "ይህንን ተሽከርካሪ ከዝርዝርዎ ውስጥ ማስወገድዎን እርግጠኛ ነዎት? ይህ እርምጃ ሊመለስ የማይችል ነው።",
    deleteCar: "መኪናውን ሰርዝ",

    // Admin Users
    userManagement: "የተጠቃሚዎች አስተዳደር",
    manageSystemAccess: "የስርዓት መዳረሻን እና ሚናዎችን ያስተዳድሩ",
    searchUsersPrompt: "ተጠቃሚዎችን በስም ወይም በኢሜይል ይፈልጉ...",
    userDetails: "የተጠቃሚ ዝርዝሮች",
    loadingUserDatabase: "የተጠቃሚዎች ዳታቤዝ በመጫን ላይ ነው...",
    noMatchingUsers: "ምንም ተዛማጅ ተጠቃሚ አልተገኘም",
    suspendUser: "ተጠቃሚን አግድ",
    activateUser: "ተጠቃሚን አንቃ",
    deleteAccount: "መለያ ሰርዝ",
    areYouSureDeleteUser: "ይህንን ተጠቃሚ በቋሚነት መሰረዝዎን እርግጠኛ ነዎት? ይህ እርምጃ ሊመለስ የማይችል ነው።",
    suspensionReason: "የመታገጃ ምክንያት",
    confirmSuspension: "እገዳውን ያረጋግጡ",
    suspensionPrompt: "እባክዎን ይህንን መለያ ለማገድ ምክንያት ይስጡ። ተጠቃሚው ወዲያውኑ ከመድረሻ ይታገዳል።",

    // Admin Lottery
    lotteryManagement: "የሎተሪ አስተዳደር",
    activeDraw: "ንቁ እጣ",
    lotteryControl: "የሎተሪ መቆጣጠሪያ",
    activePrize: "ንቁ ሽልማት",
    range: "ክልል",
    stopLottery: "ሎተሪውን ያቁሙ",
    numberRangeLabel: "የቁጥሮች ክልል",
    ticketPriceCalc: "የቲኬት ዋጋ",
    initializeNewDraw: "አዲስ እጣ ይጀምሩ",
    prepareForDraw: "ለእጣው ይዘጋጁ",
    drawWinnerDesc: "ሎተሪው ሲዘጋ እና ሁሉም ክፍያዎች ሲረጋገጡ ከተረጋገጡ ተሳታፊዎች መካከል በዘፈቀደ አሸናፊ መምረጥ ይችላሉ።",
    drawTheWinner: "አሸናፊውን ይምረጡ",
    lotteryConfirmed: "የተረጋገጠ",
    lotteryPending: "በጥበቃ ላይ",
    lotteryFree: "ነፃ",

    // Admin Settings - General
    generalSettings: "አጠቃላይ የስርዓት ቅንጅቶች",
    platformName: "የመድረክ ስም",
    logo: "ሎጎ",
    uploadLogo: "ሎጎ ይጫኑ",
    defaultCurrency: "መደበኛ ምንዛሬ",
    defaultLanguage: "መደበኛ ቋንቋ",
    timezone: "የሰዓት ቀጠና",
    dateFormat: "የቀን ፎርማት",
    contactInformation: "የመገናኛ መረጃ",
    contactEmail: "የመገናኛ ኢሜይል",
    contactPhone: "የመገናኛ ስልክ",
    physicalAddress: "አድራሻ",
    saveGeneralSettings: "አጠቃላይ ቅንጅቶችን አስቀምጥ",

    // Admin Settings - Security
    securityAccess: "ደህንነት እና መዳረሻ",
    enableRegistration: "የተጠቃሚ ምዝገባን ፍቀድ",
    registrationDesc: "አዳዲስ ተጠቃሚዎች መለያ እንዲፈጥሩ ይፍቀዱ",
    minPasswordLength: "ዝቅተኛ የይለፍ ቃል ርዝመት",
    sessionTimeout: "የቆይታ ገደብ (ደቂቃዎች)",
    requireUppercase: "ትልቅ ፊደላትን ይጠይቁ",
    uppercaseDesc: "የይለፍ ቃል ቢያንስ አንድ ትልቅ ፊደል መያዝ አለበት",
    requireNumbers: "ቁጥሮችን ይጠይቁ",
    numbersDesc: "የይለፍ ቃል ቢያንስ አንድ አሃዝ መያዝ አለበት",
    allowMultiLogin: "ባለብዙ መግቢያ ፍቀድ",
    multiLoginDesc: "ተመሳሳይ መለያ በበርካታ መሳሪያዎች ላይ እንዲገባ ይፍቀዱ",
    saveSecuritySettings: "የደህንነት ቅንጅቶችን አስቀምጥ",

    // Admin Settings - Lottery
    lotteryModule: "የሎተሪ ሞጁል",
    lotteryModuleDesc: "ሲጠፋ ተጠቃሚዎች ሎተሪ ማየት፣ ትኬት መግዛት ወይም ክፍያ መጫን አይችሉም።",
    lotteryConfiguration: "የሎተሪ ውቅር",
    drawFrequency: "የዕጣ ድግግሞሽ",
    autoCloseLabel: "ከዕጣ በፊት በራስ-ሰር መዝጊያ (ደቂቃ)",
    staffPermissions: "የሎተሪ ሰራተኞች ፈቃዶች",
    paymentVerificationPerm: "የክፍያ ማረጋገጫ",
    numberGenPerm: "የቁጥር ማመንጨት",
    adminOverridePerm: "የአስተዳዳሪ ማለፊያ",
    saveLotterySettings: "የሎተሪ ቅንጅቶችን አስቀምጥ",

    // Admin Settings - Operational
    operationalControls: "ተግባራዊ ቁጥጥሮች",
    operationalDesc: "ለድንገተኛ ጊዜ መዝጊያ ወይም ኦዲት ዋና መቀያየሪያዎች።",
    enableEntirePlatform: "ጠቅላላ መድረኩን አንቃ",
    platformShutdownDesc: "ማጥፋት መድረኩን ለሁሉም ተጠቃሚዎች ይዘጋል",
    maintenanceMessageLabel: "የጥገና ሁኔታ መልዕክት",
    saveOperationalSettings: "ተግባራዊ ቅንጅቶችን አስቀምጥ",

    // Admin Settings - Logs
    systemLogs: "የስርዓት ምዝግብ ማስታወሻዎች",
    allActions: "ሁሉም እርምጃዎች",
    adminOnly: "አስተዳዳሪ ብቻ",
    staffOnly: "ሰራተኞች ብቻ",
    exportCSV: "ኤክስፖርት CSV",
    noLogsFound: "ምንም ምዝግብ አልተገኘም።",

    // Admin Settings - Notifications
    notificationSettings: "የማሳወቂያ ቅንጅቶች",
    emailNotifications: "የኢሜይል ማሳወቂያዎች",
    smsNotifications: "የኤስኤምኤስ ማሳወቂያዎች",
    largePaymentAlerts: "የትልልቅ ክፍያ ማንቂያዎች",
    suspiciousActivityAlerts: "የአጠራጠሪ እንቅስቃሴ ማንቂያዎች",
    saveNotificationSettings: "የማሳወቂያ ቅንጅቶችን አስቀምጥ",

    // Admin Settings - Backup
    backupRecovery: "ምትኬ እና መልሶ ማግኛ",
    backupFrequency: "የምትኬ ድግግሞሽ",
    manualBackup: "በእጅ ምትኬ ይጀምሩ",
    remoteSnapshots: "የSQL ስናፕሾቶች",
    saveBackupSettings: "የምትኬ ቅንጅቶችን አስቀምጥ",

    // Admin Layout & Dashboard
    administration: "አስተዳደር",
    exitAdmin: "ከአስተዳዳሪው ይውጡ",
    exitLotteryStaff: "ከሎተሪ ሰራተኛ ይውጡ",
    lotteryPortal: "የሎተሪ ፖርታል",
    adminCommandCenter: "የአስተዳደር ትዕዛዝ ማዕከል",
    overviewMetrics: "አጠቃላይ መለኪያዎች",
    live: "ቀጥታ",
    review: "ግምገማ",
    totalLabel: "ጠቅላላ",
    est: "ግምት",
    platformConfiguration: "የመድረክ ውቅር",
    settings: "ቅንጅቶች",
    general: "አጠቃላይ",
    security: "ደህንነት",
    operational: "ተግባራዊ",
    logs: "ምዝግብ ማስታወሻዎች",
    notifications: "ማሳወቂያዎች",
    backup: "ምትኬ",

    // Dashboard & Sidebar
    navGenerateNumbers: "ቁጥሮችን ይፍጠሩ",
    navLotteryPayments: "የሎተሪ ክፍያዎች",
    navNumberBoard: "የቁጥር ሰሌዳ",
    navParticipants: "ተሳታፊዎች",
    navUsers: "ተጠቃሚዎች",
    navManagementPortal: "የአስተዳደር ፖርታል",
    navCoreManagement: "ዋና አስተዳደር",
    navLotteryOperations: "የሎተሪ ስራዎች",
    navTerminateSession: "ክፍለ ጊዜ አቋርጥ",
    navEngineHealthy: "ማሽን ጤናማ ነው",
    navStaffPortal: "የሰራተኛ ፖርታል",
    navGlobalAdmin: "አጠቃላይ አስተዳዳሪ",
    navSystemId: "የስርዓት መለያ",
    navDashboard: "ዳሽቦርድ",

    // Notifications Page
    notifMarkAllAsRead: "ሁሉንም እንደተነበበ ምልክት አድርግ",
    notifLoading: "ማሳወቂያዎችን በማምጣት ላይ...",
    notifNoNotificationsYet: "ምንም ማሳወቂያዎች የሉም",
    notifWhenUpdatesAppear: "ዝመናዎች ሲኖሩዎት እዚህ ይታያሉ።",
    notifMarkAsRead: "እንደተነበበ ምልክት አድርግ",
    notifDelete: "ሰርዝ",

    // Admin Dashboard
    lotteryOpsPortal: "የሎተሪ ስራዎች ፖርታል",
    dashAdminCommandCenter: "የአስተዳደር ትዕዛዝ ማዕከል",
    platformRunningOpt: "የእርስዎ መድረክ በጥሩ አቅም እየሰራ ነው። ከታች ያሉትን የቅርብ ጊዜ የእንቅስቃሴ ሪፖርቶች ይመልከቱ።",
    systemSecure: "ስርዓቱ ደህንነቱ የተጠበቀ ነው",
    liveIntelligence: "ቀጥታ መረጃ",
    realTimeData: "የእውነተኛ ጊዜ ውሂብ",
    actionRequired: "እርምጃ ያስፈልጋል",
    fourThisWeek: "በዚህ ሳምንት +4",
    dashEstRevenue: "የገቢ ግምት",
    etbTotal: "ጠቅላላ ብር",
    recentEvents: "የቅርብ ጊዜ ክስተቶች",
    viewFullAudit: "ሙሉ ኦዲት ይመልከቱ",
    gatheringLogs: "የእንቅስቃሴ ምዝግብ ማስታወሻዎችን በማሰባሰብ ላይ...",
    newLotteryCreated: "አዲስ ሎተሪ ተፈጥሯል",
    securityPolicyUpdated: "የደህንነት ፖሊሲ ዘምኗል",
    paymentManualOverride: "በእጅ የተደረገ ክፍያ ማጽደቅ",
    adminDiagnosticsSweep: "አስተዳዳሪው የስርዓት መመርመሪያዎችን ጠራርጎ በማከናወን በመጠባበቅ ላይ ያሉ ትኬቶችን አረጋግጧል።",
    operations: "ስራዎች",
    fastLotterySetup: "ፈጣን የሎተሪ ዝግጅት",
    initializationTools: "ማስጀመሪያ መሳሪያዎች",
    newDraw: "አዲስ ዕጣ",

    // Admin Lottery Subpages
    alGenerateNumbers: "ቁጥሮችን ይፍጠሩ",
    alSetRangeAndPrize: "የቁጥር ክልል እና ሽልማት ያቀናብሩ — ስርዓቱ ሁሉንም ትኬቶች ወዲያውኑ ይፈጥራል።",
    alMainPrize: "ዋና ሽልማት",
    alTicketPriceSettings: "የቲኬት ዋጋ በቅንብሮች በኩል",
    alPrizeExample: "ለምሳሌ፡- 2024 Toyota Camry",
    alInitializing: "በማስጀመር ላይ...",
    alDrawingWinner: "አሸናፊ በማውጣት ላይ...",
    alRequiresConfirmedTicket: "ለመሳል ቢያንስ 1 የተረጋገጠ የቲኬት ክፍያ ያስፈልጋል።",
    alOneLuckyWinner: "አንድ ባለዕድል ያሸንፋል! ከመሳልዎ በፊት ሁሉም ክፍያዎች መረጋገጣቸውን ያረጋግጡ።",
    
    lpLotteryParticipants: "የሎተሪ ተሳታፊዎች",
    lpActiveDraw: "የአሁኑ ዕጣ:",
    lpSearchPlaceholder: "በስም ወይም በትኬት ቁጥር ይፈልጉ…",
    lpTotalParticipants: "ጠቅላላ ተሳታፊዎች",
    lpConfirmedTickets: "የተረጋገጡ ትኬቶች",
    lpPendingReview: "ግምገማ በመጠባበቅ ላይ",
    lpNoParticipantsMatching: "ከፍለጋዎ ጋር የሚዛመዱ ተሳታፊዎች የሉም።",
    lpNoVerifiedParticipants: "እስካሁን የተረጋገጠ ተሳታፊ የለም።",
    lpParticipantsAppearOnce: "ክፍያ ከተፈጸመ በኋላ ተሳታፊዎች ይታያሉ።",
    lpParticipant: "ተሳታፊ",
    lpTicketNumbers: "የቲኬት ቁጥሮች",
    lpCount: "ብዛት",
    lpJoined: "የተቀላቀለበት",
    lpShowingParticipants: "ከ",
    lpOf: "ውስጥ በማሳየት ላይ -",
    lpClearSearch: "ፍለጋ አጽዳ",
    
    payLotteryPayments: "የሎተሪ ክፍያዎች",
    payReviewVerify: "የተጠቃሚዎችን የሎተሪ ቲኬት ክፍያ ደረሰኞች ይገምግሙ እና ያረጋግጡ።",
    payRefresh: "አድስ",
    payAll: "ሁሉም",
    payTotal: "ድምር",
    payNoPaymentsFilter: "ከማጣሪያዎ ጋር የሚዛመድ ክፍያ የለም።",
    payNoLotteryPayments: "የሎተሪ ክፍያ መዝገብ አልተገኘም።",
    payPaymentsAppearOnce: "ተጠቃሚዎች ደረሰኞቻቸውን ሲያስገቡ ክፍያዎች ይታያሉ።",
    payUser: "ተጠቃሚ",
    payMethod: "ዘዴ",
    payTicket: "ቲኬት",
    payReceipt: "ደረሰኝ",
    payStatus: "ሁኔታ",
    payActions: "ድርጊቶች",
    payApprove: "አጽድቅ",
    payReject: "አትቀበል",
    payView: "አሳይ",

    glNumberBoard: "የቁጥር ሰሌዳ",
    glLiveView: "የሁሉንም የቲኬት ቁጥሮች እና ለሚቀጥለው ዕጣ ያላቸውን የአሁኑ ሁኔታ የቀጥታ እይታ።",
    glActiveDrawText: "የአሁኑ ዕጣ",
    glRangeText: "ክልል",
    glNumbersGeneratedAuto: "አስተዳዳሪው አዲስ ሎተሪ ሲፈጥር ቁጥሮች በራስ-ሰር ይፈጠራሉ።",
    glTotalNumbers: "ጠቅላላ ቁጥሮች",
    glNoActiveLottery: "ምንም ንቁ ሎተሪ አልተገኘም።",
    glGoToLotteryManagement: "አዲስ ዕጣ ለመፍጠር እና ለመጀመር ወደ ሎተሪ ማስተዳደሪያ ይሂዱ።",
    glNoNumbersMatch: "ከአሁኑ ማጣሪያ ጋር የሚዛመድ ቁጥር የለም።",

    // Lottery User Pages
    l_syncingDraw: "ከቀጥታ ዕጣ ጋር በማመሳሰል ላይ...",
    l_platformVerified: "በመድረኩ የተረጋገጠ",
    l_premiumVehicleExp: "ፕሪሚየም የተሽከርካሪ ተሞክሮ",
    l_secureBlockchain: "ደህንነቱ የተጠበቀ የምርጫ ስርዓት",
    l_activeNow: "አሁን ንቁ ነው",
    l_noActiveSweepstakes: "ምንም ንቁ ሎተሪ የለም",
    l_preparingNextDraw: "ቀጣዩን ታላቅ ዕጣ እያዘጋጀን ነው። እባክዎ በቅርቡ ተመልሰው ይፈትሹ።",
    l_numbersReserved: "ቁጥሮች ተይዘዋል",
    l_reservedSuccess: "ቁጥሮችን በተሳካ ሁኔታ አስቀምጠዋል፡",
    l_finalizeEntry: "ደረሰኝዎን በማስገባት ምዝገባዎን ያጠናቅቁ።",
    l_backToLottery: "ወደ ሎተሪ ተመለስ",
    l_selectionStep: "የምርጫ ደረጃ",
    l_pickLuckyPath: "የዕድልዎን መንገድ ይምረጡ",
    l_syncingBoard: "የቁጥር ሰሌዳውን በማመሳሰል ላይ...",
    l_restrictedAccess: "የተገደበ መዳረሻ",
    l_managementRestriction: "የአስተዳደር መለያዎች እንዲሳተፉ አይፈቀድላቸውም።",
    l_boardOffline: "ሰሌዳው ከመስመር ውጭ ነው",

    // Profile Page
    logout: "ወጥቷል",
    logoutSuccess: "በተሳካ ሁኔታ ወጥተዋል።",
    profileSynchronized: "ለውጦቹ በተሳካ ሁኔታ ተቀምጠዋል።",
    navTickets: "የኔ ቲኬቶች",

    // Auth Extended
    authEncryptedAccess: "የተመሰጠረ የመግቢያ ነጥብ",
    authPremiumTitle: "የእርስዎ ፕሪሚየም",
    authJourneyStarts: "ጉዞ እዚህ ይጀምራል።",
    authLoginDesc: "ዳሽቦርድዎን ለመድረስ፣ በሎተሪዎች ለመሳተፍ እና ፍላጎቶችዎን ለማስተዳደር ይግቡ።",
    authVettedAssets: "የተረጋገጡ ንብረቶች",
    authFairPlay: "ፍትሃዊ ጨዋታ",
    authAuthenticatedAccess: "የተረጋገጠ መግቢያ",
    authEstablishingSession: "ክፍለ ጊዜ በመመስረት ላይ...",
    authWelcomeBackMsg: "እንኳን ደህና መጡ",
    authSecureSession: "ደህንነቱ የተጠበቀ ክፍለ ጊዜ ተመስርቷል።",
    authAccessDenied: "መግቢያ ተከልክሏል",
    authNetworkError: "የአውታረ መረብ ስህተት",
    authConnectionFailed: "ደህንነቱ የተጠበቀ ግንኙነት አልተሳካም።",
    authInitializationIdentity: "ማንነትን በማስጀመር ላይ...",
    authSecureNodeInitialization: "ደህንነቱ የተጠበቀ ማንነት ማስጀመር",
    authJoinEliteNetwork: "Elite አውታረ መረብን ይቀላቀሉ።",
    authRegisterDesc: "ልዩ የሎተሪ ዕድሎችን፣ የኪራይ አገልግሎቶችን እና የሽያጭ ገበያ ቦታን ለማግኘት አካውንት ይፍጠሩ።",
    authTransparentDraw: "ግልጽ የዕጣ አወጣጥ ፕሮቶኮል",
    authVerifiedAssetNetwork: "የተረጋገጠ የንብረት አውታረ መረብ",
    authSeamlessAssetManagement: "እንከን የለሽ የንብረት አያያዝ",
    authCreateIdentity: "ማንነት ይፍጠሩ",
    authAccountInitialized: "አካውንት ተጀምሯል",
    authIdentityVerified: "ማንነት ተረጋግጧል። አሁን መግባት ይችላሉ።",
    authRegistrationBlocked: "ምዝገባ ታግዷል",
    authCredentialConflict: "የመረጃ ግጭት ተገኝቷል።",
    authConnectionError: "የግንኙነት ስህተት",
    authSecureNodeRegistration: "ደህንነቱ የተጠበቀ ምዝገባ አልተሳካም።",

    // Payment Extended
    paySecureCheckout: "ደህንነቱ የተጠበቀ ክፍያ",
    payRestrictedAccess: "የተገደበ መዳረሻ",
    payManagementRestriction: "የስርዓቱን ታማኝነት ለመጠበቅ የአስተዳዳሪ አካውንቶች ክፍያ መፈጸም ወይም በሎተሪ መሳተፍ አይችሉም።",
    paySelectionReservation: "የተያዘ ቦታ ይምረጡ",
    payWhichReservation: "ለየትኛው ይዞታ ነው ክፍያ የሚፈጽሙት?",
    payNoReservedFound: "ምንም የተያዘ ቁጥር አልተገኘም",
    payPickConfirmNumbers: "ክፍያ ከመፈጸምዎ በፊት በሎተሪ ሰሌዳው ላይ ቁጥሮችዎን መምረጥ እና ማረጋገጥ አለብዎት።",
    payGoToBoard: "ወደ ቁጥር ሰሌዳ ይሂዱ",
    payAmountDue: "የሚከፈልበት መጠን",
    payGateway: "የክፍያ መተላለፊያ",
    payValidationMedia: "የማረጋገጫ ሚዲያ",
    payReplaceImage: "ምስል ይቀይሩ",
    payStreamingData: "ውሂብ በመላክ ላይ...",
    payValidatingSession: "ክፍለ ጊዜን በማረጋገጥ ላይ...",
    payOfficialAccount: "ይፋዊ አካውንት",
    payTransferInstructions: "እባክዎን ለትኬቶችዎ ትክክለኛውን መጠን ያስተላልፉ። ከመላክዎ በፊት የአካውንት ቁጥሩን ደግመው ያረጋግጡ። ለማረጋገጥ ጥራት ያላቸው ምስሎች ያስፈልጋሉ።",
    payCBE: "የኢትዮጵያ ንግድ ባንክ (ንግድ ባንክ)",
    payTelebirrWallet: "ቴሌብር ዋሌት",
    payDriveHubAccount: "የድራይቭ ሀብ ሎተሪ አካውንት",
    payAdminTerminal: "የአስተዳዳሪ ክፍያ ተርሚናል",
    payRecentActivity: "የቅርብ ጊዜ እንቅስቃሴ",
    payFetchingLedger: "መረጃ በማምጣት ላይ...",
    payNoTransactionHistory: "ምንም የግብይት ታሪክ የለም",
    payUnderReview: "በግምገማ ላይ",
    payVerifyingReceipt: "ደረሰኝ በማረጋገጥ ላይ",
    payAwaitingPayment: "ክፍያን በመጠባበቅ ላይ",
    payPaymentRejected: "ክፍያ ውድቅ ተደርጓል",
    payTicketEntry: "የቲኬት ግቤት",

    appSuffix: "የመኪና ሽያጭ እና ኪራይ",

    // Admin Extended
    adminSystemCore: "የስርዓት እምብርት",
    adminSettingsDesc: "የመድረክዎን ተሞክሮ እና የአሰራር መለኪያዎችን ያስተካክሉ።",
    adminGeneralDesc: "ለመድረክዎ መገኘት መሰረታዊ ውቅር።",
    adminSecurityDesc: "የይለፍ ቃል ፖሊሲዎችን እና የክፍለ ጊዜ ባህሪን ያስገድዱ።",
    adminLotteryDesc: "ለካርታ ሎተሪዎችዎ ዋና መካኒኮች እና ዋጋ።",
    adminOperationalDesc: "ከፍተኛ ደረጃ የመድረክ መቀየሪያዎች እና የጥገና ሁኔታ።",
    adminNotificationsDesc: "አስተዳዳሪዎች እና ተጠቃሚዎች እንዴት እና መቼ እንደሚነገሩ ይቆጣጠሩ።",
    adminBackupDesc: "ውሂብዎን በደመና ቅጽበታዊ ገጽ እይታዎች እና በእጅ በሚደረጉ መጠባበቂያዎች ይጠብቁ።",
    adminLogsDesc: "የወሳኝ አስተዳደራዊ እና የሰራተኛ እርምጃዎች የኦዲት መሄጃ።",
    adminStartingBackup: "ምትኬ በመጀመር ላይ",
    adminTriggeringBackup: "በእጅ የሂሳብ መረጃ ምትኬን በማነሳሳት ላይ...",
    adminBackupFinalized: "ምትኬ ተጠናቅቋል",
    adminBackupSuccess: "የርቀት SQL ምትኬ በተሳካ ሁኔታ ተፈጥሯል።",
    adminMaxTicketsPerUser: "ከፍተኛ ትኬቶች/ተጠቃሚ",
    adminManualStaffTriggered: "በእጅ (በሰራተኛ የሚነሳ)",
    adminWeeklyAuto: "ሳምንታዊ አውቶማቲክ",
    adminDailyAuto: "ዕለታዊ አውቶማቲክ",
    adminLotteryEngine: "የሎተሪ ሞተር",
    adminToggleTicketing: "ትኬት መቁረጥን እና ዕጣዎችን ይቀይሩ",
    adminMaintenancePlaceholder: "በአሁኑ ጊዜ የታቀደ የጥገና ስራ እየሰራን ነው። እባክዎ ቆይተው ይመልከቱ።",
    adminEmailEngine: "የኢሜይል ሞተር",
    adminSmsGateway: "የኤስኤምኤስ መግቢያ",
    adminSecurityAlerts: "የደህንነት/አጠራጣሪ ማንቂያዎች",
    adminAutoSnapshotSchedule: "ራስ-ሰር የቅጽበታዊ ገጽ እይታ ፕሮግራም",
    adminRollbackSystem: "ስርዓቱን ወደ ኋላ ይመልሱ",
    adminEverywhere: "በሁሉም ቦታ",
    adminNoLogsMatching: "ከአሁኑ ማጣሪያዎችዎ ጋር የሚዛመዱ ምዝግብ ማስታወሻዎች የሉም።",
    adminRefresh: "አድስ",
    adminAddStaff: "ሰራተኛ ጨምር",
    adminProvisionStaff: "የሰራተኛ መለያ ፍጠር",
    adminStaffDescription: "ለሎተሪ ሰራተኛ ድርሻ ብቻ ደህንነቱ የተጠበቀ መግቢያ ያመነጩ። ተራ ተጠቃሚዎች ይህንን መዳረሻ መጠየቅ አይችሉም።",
    adminFullName: "ሙሉ ስም",
    adminWorkEmail: "የስራ ኢሜይል",
    adminInitialPassword: "የመጀመሪያ ይለፍ ቃል",
    adminCreateStaff: "ሰራተኛ ፍጠር",
    adminTotalUsers: "ጠቅላላ ተጠቃሚዎች",
    adminActiveUsers: "ንቁ",
    adminSuspendedUsers: "የታገዱ",
    adminStaffMembers: "የሰራተኛ አባላት",
    adminConfirmDeletion: "መሰረዙን ያረጋግጡ",
    adminStaffCreated: "ሰራተኛ ተፈጥሯል",
    adminStaffSuccess: "አዲሱ የሎተሪ ሰራተኛ መለያ በተሳካ ሁኔታ ተፈጥሯል።",
    adminValidationError: "የማረጋገጫ ስህተት",
    adminAllFieldsRequired: "ሁሉም መስኮች የግድ አስፈላጊ ናቸው።",
    adminPasswordLength: "የይለፍ ቃል ቢያንስ 6 ቁምፊዎች መሆን አለበት።",
    adminGenerationFailed: "ምርት አልተሳካም",
    adminCouldNotCreateStaff: "የሰራተኛ መለያ መፍጠር አልተቻለም።",
    adminAccountActivated: "መለያ ተለቋል",
    adminAccountActivatedDesc: "መለያው አሁን ንቁ ነው።",
    adminUserSuspended: "ተጠቃሚው ታግዷል",
    adminAccountRevoked: "የመለያ መዳረሻ ተሰርዟል።",
    adminUserDeleted: "ተጠቃሚው ተሰርዟል",
    adminAccountRemoved: "መለያው በተሳካ ሁኔታ ተወግዷል።",
    role: "ድgrid",
    adminConfirmSuspensionDesc: "ተጠቃሚውን ማገድዎን እርግጠኛ ነዎት?",
    adminSuspensionReasonPlaceholder: "ምሳሌ፡ የአገልግሎት ደንቦችን መጣስ...",
    processing: "በማከናወን ላይ...",
    generating: "በማመንጨት ላይ...",
    profVerifiedProfile: "የተረጋገጠ መገለጫ",
    profMemberSince: "የመድረክ አባል ከ 2026 ጀምሮ",
    profEntries: "ተሳትፎዎች",
    profRentals: "ኪራዮች",
    profSave: "አስቀምጥ",
    profEdit: "አስተካክል",
    profSecurityIdentity: "ደህንነት እና ማንነት",
    profProfileConfiguration: "የመገለጫ ውቅር",
    profFirstName: "መጀመሪያ ስም",
    profLastName: "የአያት ስም",
    profEmailTerminal: "የኢሜይል ተርሚናል",
    profContactConnection: "የግንኙነት መስመር",
    profSyncChanges: "ለውጦችን አመሳስል",
    profStatusLevel: "የሁኔታ ደረጃ",
    profCoreContributor: "ዋና አስተዋጽኦ አድራጊ",
    profProgressToPlatinum: "ወደ ፕላቲነም እድገት",
    profRecentActivity: "የቅርብ ጊዜ የዕጣ ዝርዝር",
    profSynchronizedLedger: "ሙሉ መዝገብ",
    profFinancialHistory: "የፋይናንስ እና የቶከን ታሪክ",
    profRequestingArchives: "ማህደሮችን በመጠየቅ ላይ...",
    profNoActiveHistory: "ምንም ንቁ ታሪክ አልተገኘም",
    profStartJourney: "ንቁ ሎተሪዎችን በማየት ጉዞዎን ይጀምሩ።",
    profExploreDraws: "ዕጣዎችን ያስሱ",
    profEndOfHistory: "የታሪክ ፍሰት መጨረሻ",
    profRequestAudit: "ሙሉ የኦዲት መረጃ ይጠይቁ",
    profFleetAccess: "የመኪናዎች መዳረሻ",
    profActiveRentalContracts: "ጠቅላላ ንቁ የኪራይ ውሎች፡",
    profManageFleet: "ተሽከርካሪዎችን ያስተዳድሩ",
    profPendingEntry: "በጥበቃ ላይ",
    profConfirmedEntry: "የተረጋገጠ ተሳትፎ",
    profRejectedEntry: "ተቀባይነት ያላገኘ",
    profVerifyingReceipt: "ደረሰኝ በማረጋገጥ ላይ",
    profAwaitingPayment: "ክፍያ በመጠባበቅ ላይ",
    profWinner: "አሸናፊ",
    profStandardEntry: "የሎተሪ ተሳትፎ መግቢያ",
  },
  om: {
    // Nav
    home: "Fuula Jalqabaa",
    cars: "Konkolaataa",
    rentals: "Kireeffannaa",
    lottery: "Lootarii",
    contact: "Nu Quunnamaa",
    login: "Seeni",
    systemMaintenance: "Sirni kun suphaa irra jira",
    retry: "Irra deebi'ii yaali",
    signUp: "Galmaa'i",
    carsForSale: "Konkolaataa Gurgurtaaf",
    carsForRent: "Konkolaataa Kireeffannaaf",

    // Hero
    heroTagline: "IDDOO FILANNOO KONKOLAATTOO PIRIIMIYEEMII",
    heroTitle: "Gech",
    heroTitleSub: "",
    heroDesc: "Konkolaattota piriimiyeemii bakka tokkotti bari፣ biti፣ kiraayeffadhu፣ akkasumas mo'adhu. Gabaa konkolaattootaa isa filatamaa Itoophiyaa",
    browseFleet: "Tarreeffama dhiyeessii",
    winACar: "Konkolaataa mo'adhu",
    scrollToExplore: "Bal'inaan arguuf gara gadii deemi",
    browseCars: "Konkolaataa Ilaali",
    enterLottery: "Lootarii Seeni",
    vehicles: "Konkolaataawwan",
    happyClients: "Maamiltootaa Gammadan",
    lotteryDraws: "Qurxii Lootarii",

    // Featured
    featured: "Filataman",
    handpickedVehicles: "Konkolaataawwan Filataman",
    viewAll: "Hunda ilaali",
    viewDetails: "Bal'inaan ilaali",
    sale: "Gurgurtaa",
    rental: "Kireeffannaa",

    // Services
    whatWeOffer: "Maal Dhiyeessina",
    threeWays: "Karaa Sadiin Oofuu",
    buyACar: "Konkolaataa Bitadhu",
    buyACarDesc: "Konkolaataawwan piriimiyeemii gatii ifaa fi ibsa bal'aa waliin sakattaʼi.",
    rentACar: "Konkolaataa Kireeffadhu",
    rentACarDesc: "Kireeffannaa guyyaa gatii dorgomaa qabu. Har'a fuudhi, yeroo xumurtu deebisi.",
    carLottery: "Lootarii Konkolaataa",
    carLotteryDesc: "Lakkoofsa carraa kee filadhu, tikeetii kee kaffalti, badhaasa dinqisiisaa moʼachuuf carraa argadhu.",

    // Lottery section (landing)
    howItWorks: "Akkamitti Hojjeta",
    winYourNextRide: "Konkolaataa Itti Aanu Kee Moʼi",
    lotteryLandingDesc: "Lootariin konkolaataa keenyaa namoota hundaaf carraa walqixaa konkolaataa piriimiyeemii moʼachuuf kenna.",
    pickYourNumbers: "Lakkoofsa Kee Filadhu",
    pickNumbersDesc: "Lakkoofsa argaman keessaa filadhu — tokko tokkoon kan kee qofa.",
    confirmAndPay: "Mirkaneessi & Kaffali",
    confirmPayDesc: "Ragaa kaffaltii kee galchii mirkaneessa bulchiinsaa eegi.",
    winBig: "Guddaa Moʼi",
    winBigDesc: "Yeroo qurxiin godhamtu, lakkoofsoonni walsiman badhaasa guddaa fudhatu.",
    enterTheLottery: "Lootarii Seeni",

    // Trust
    verifiedVehicles: "Konkolaataa Mirkanaaʼe",
    averageResponse: "Deebii Giddugaleessa",
    customerRating: "Sadarkaa Maamiltoo",

    // Lottery page
    lotteryTagline: "Lootarii Gech",
    lotteryTitle: "Lakkoofsa Filadhu, Konkolaataa Moʼi",
    lotteryDesc: "Lootariin konkolaataa keenyaa carraa konkolaataa piriimiyeemii gara manaatti oofuuf ta'a. Lakkoofsa carraa keessan filadhaa, tikeetii keessan mirkaneessaa, qurxii eegadhaa.",
    currentDraw: "CARRAA AMMAA",
    grandPrize: "Badhaasa Guddaa: Fuulduratti Kan Ibsamu",
    ticketPrice: "GATII TIKKEETTII",
    numberRange: "Daangaa Lakkoofsa",
    ticketsLeft: "Tikeetii Hafe",
    selectYourNumbers: "Lakkoofsa Keessan Filadhaa",
    step: "Tarkaanfii",
    chooseNumbers: "Lakkoofsa Keessan Filadhaa",
    chooseNumbersDesc: "Saaphana lakkoofsa keessa sakattaʼaa fi lakkoofsa kamiyyuu hin qabamne filadhaa.",
    submitPayment: "Kaffaltii Galchaa",
    submitPaymentDesc: "Ragaa kaffaltii keessan lakkoofsa wabii waliin galchaa. Bulchiinsi kaffaltii keessan ni mirkaneessa.",
    waitForDraw: "Qurxii Eegadhaa",
    waitForDrawDesc: "Erga tikeetiin hundi gurguramee ykn beellama booda, lakkoofsa moʼataa kallattiin ni harkifna.",
    lotteryRules: "Seerota Lootarii",
    rule1: "Hirmaataan tokko tokko qurxii tokkootti tikeetii hanga 5 bitachuu ni dandaʼa.",
    rule2: "Lakkoofsoonni kan qabaman yeroo kaffaltiin fudhatamu — yeroo filatanitti miti.",
    rule3: "Guyyaan qurxii yeroo tikeetiin hundi gurguramee ykn beellamni gaʼu ni beeksifama.",
    rule4: "Moʼattoonni badhaasa isaanii guyyaa 30 keessatti gaafachuu qabu.",
    rule5: "Murtiin hundi bulchiinsa Gech kan xumuraati.",

    // Lottery Select
    backToLottery: "Gara Lootarii Deebi'i",
    pickUpTo5: "Hanga lakkoofsa 5 filadhu. Lakkoofsoonni bifa daalachaa qabaman duraan qabamaniiru.",
    available: "Argamaa",
    selected: "Filatame",
    taken: "Qabame",
    yourSelection: "Filannoo Kee",
    noNumbersSelected: "Ammaaf lakkoofsi hin filatamne.",
    tickets: "Tikeetiiwwan",
    priceEach: "Gatii tokkoo",
    total: "Ida'ama",
    confirmSelection: "Filannoo Mirkaneessi",
    numbersReserved: "Lakkoofsoonni Qabamaniiru!",
    youSelected: "Kan filattes:",
    completePayment: "Hirmaannaa kee mirkaneessuuf kaffaltii kee xumuri.",
    goToPayment: "Gara Kaffaltii Deemi",

    // Cars pages
    inventory: "Kuusaa",
    searchVehicles: "Konkolaataa barbaadi...",
    filters: "Calaqqisiisaa",
    brand: "Maqaa",
    all: "Hunda",
    noVehiclesMatch: "Konkolaataan ulaagaa kee guutu hin argamne.",
    clearFilters: "Calaqqisiisaa Haquu",
    forSale: "Gurgurtaaf",
    forRent: "Kireeffannaaf",
    sold: "Gurgurame",
    rented: "Kireeffatame",
    unavailable: "Hin argamu",
    contactToBuy: "Bituuf Nu Quunnamaa",
    noLongerAvailable: "Dhaabbateera",
    bookRental: "Kireeffannaa Qabadhu",
    currentlyRented: "Yeroo ammaa kireeffatameera",
    paymentInfo: "Odeeffannoo Kaffaltii",
    backToSales: "Gara Gurgurtaa Deebi'i",
    backToRentals: "Gara Kireeffannaa Deebi'i",
    vehicleNotFound: "Konkolaataan hin argamne",
    backToListings: "Gara Tarreetti Deebi'i",
    year: "Waggaa",
    mileage: "KM",
    fuel: "Boba'aa",
    transmission: "Dabarsa",
    seats: "Teessoo",
    rentNow: "Amma Kireeffadhu",
    searchRentals: "Kireeffannaa barbaadi...",
    rentalsLabel: "Kireeffannaa",

    // Car Detail
    specifications: "Ibsa Bal'aa",

    // Payment
    payment: "Kaffaltii",
    paymentPageDesc: "Bitaa ykn hirmaannaa lootarii keessan mirkaneessuuf ragaa kaffaltii keessan galchaa.",
    submitPaymentReceipt: "Ragaa Kaffaltii Galchaa",
    referenceNumber: "Lakkoofsa Wabii",
    receiptImage: "Suuraa Ragaa",
    clickToUpload: "Ragaa galchuuf tuqaa",
    uploadHint: "PNG, JPG hanga 5MB",
    submitReceipt: "Ragaa Galchaa",
    paymentHistory: "Seenaa Kaffaltii",
    pending: "Eeggataa",
    approved: "Fudhatame",
    rejected: "Didame",
    homeLink: "Fuula Jalqabaa",

    // Dashboard
    welcomeBack: "Baga nagaan deebite",
    userAccountTier: "Miseensa Piriimiyeemii",
    dashboardSubtitle: "Giddu-gala to'annoo keessan konkolaataa piriimiyeemii bitachuu fi lootarii hirmaannaa keessaniif.",
    activitySummary: "Cuunfaan sochii keessanii as dhiyaateera.",
    activeRentals: "Kireeffannaa Hojii irra jiru",
    lotteryEntries: "Hirmaannaa Lootarii",
    pendingPayments: "Kaffaltii Eeggataa",
    quickActions: "Tarkaanfiiwwan Ariifataa",
    browseCarsForSale: "Konkolaataa Gurgurtaaf Ilaali",
    enterLotteryAction: "Lootarii Seeni",
    myProfile: "Piroofaayilii Koo",
    activeEntries: "Hirmaannaa Hojii Irra Jiru",
    verifiedTickets: "Tikkeettii Mirkanaa'e",
    awaitingVerification: "Mirkaneessa Eeggataa",
    savedVehicles: "Konkolaataa Olka'ame",
    watchingStatus: "Haala Hordofaa Jiru",

    // Auth
    welcomeBackLogin: "Baga Nagaan Deebitee",
    signInToAccount: "Herrega Gech keetti seeni",
    demoAccounts: "Herrega Agarsiisaa",
    email: "Imeelii",
    password: "Jecha Darbii",
    forgotPassword: "Jecha darbii dagattee?",
    signIn: "Seeni",
    noAccount: "Herrega hin qabduu?",
    createOne: "Uumi",
    createAccount: "Herrega Uumi",
    joinGech: "Bituuf, kireeffachuuf ykn moʼachuuf Gech makali",
    firstName: "Maqaa",
    lastName: "Maqaa Abbaa",
    phone: "Bilbila",
    haveAccount: "Duraan herrega qabdaa?",
    signInLink: "Seeni",
    atLeast8: "Yoo xiqqaate arfii 8",
    containsNumber: "Lakkoofsa of keessaa qaba",
    containsUppercase: "Qubee guddaa of keessaa qaba",

    // Footer
    footerDesc: "Gurgurtaa, kireeffannaa fi qurxii lootarii konkolaataatiif michuu amanamaa keessan.",
    quickLinks: "Geessituu Ariifataa",
    aboutUs: "Waa'ee Keenyaa",
    account: "Herrega",
    logIn: "Seeni",
    register: "Galmaaʼi",
    dashboard: "Daashboordii",
    contactFooter: "Nu Quunnamaa",
    allRightsReserved: "Mirgi hundi kan eegame.",

    // Contact page
    contactTagline: "Nu Quunnamaa",
    contactTitle: "Nu Quunnamaa",
    contactDesc: "Konkolaataa, kireeffannaa ykn lootarii irratti gaaffii qabduu? Isin dhagaʼuuf ni gammadna.",
    phoneLabel: "Bilbila",
    phoneTap: "Mobaayila irratti bilbiluuf tuqi",
    telegramLabel: "Teleegiraamii",
    telegramTap: "Apiliikeeshinii Teleegiraamii bana",
    emailLabel: "Imeelii",
    addressLabel: "Teessoo",
    addressValue: "Jemo3 buufata boba'aa Taf bukkee",
    hoursLabel: "Saʼaatii Hojii",
    hoursValue: "Wiixata–Sanbata: 8:00 WD – 6:00 WB",
    savedCars: "Konkolaataa Olka'ame",
    noSavedCars: "Hamma yoonaatti konkolaataa olkaa'ame hin qabdu.",
    signInToSave: "Konkolaataa olkaasuuf maaloo seenaa.",

    // Admin
    adminDashboard: "Daashboordii Bulchiinsaa",
    management: "Bulchiinsa",
    lotteryOps: "Hojii Lootarii",
    adminCars: "Bulchiinsa Konkolaataa",
    adminUsers: "Bulchiinsa Fayyadamtootaa",
    adminLottery: "Qindaa'ina Lootarii",
    lotteryPayments: "Kaffaltii Lootarii",
    generateNumbers: "Lakkoofsa Maddisiisuu",
    participants: "Hirmaattota",
    adminSettings: "Qindaa'ina Sirnaa",
    totalVehicles: "Waliigala Konkolaataa",
    estRevenue: "Galii Tilmaamamuu",
    goodMorning: "Akkam bulte",
    goodAfternoon: "Akkam oolte",
    goodEvening: "Akkam galte",

    // Admin Common
    cancel: "Haquu",
    actions: "Gochaawwan",
    confirmDeletion: "Haqamuu Mirkaneessi",
    delete: "Haquu",

    // Admin Cars
    carManagement: "Bulchiinsa Konkolaataa",
    addEditRemoveVehicles: "Konkolaataa kuusaa keessaa dabali, sirreessi ykn haqi",
    addVehicle: "Konkolaataa Dabali",
    searchByName: "Maqaadhaan barbaadi...",
    vehicleDetails: "Ibsa Konkolaataa",
    priceBirr: "Gatii (Birr)",
    noVehiclesInventory: "Kuusaa keessa konkolaataan hin jiru",
    editVehicleDetails: "Ibsa Konkolaataa Sirreessi",
    addNewVehicle: "Konkolaataa Haaraa Dabali",
    make: "Oomishamaa",
    model: "Moodela",
    dealType: "Gosa Waliigaltee",
    availability: "Argamaa",
    vehicleShowcaseImage: "Suuraa Konkolaataa",
    clickToUploadImage: "Suuraa fe'uuf as tuqi",
    vehicleDescription: "Ibsa Konkolaataa",
    updateVehicle: "Konkolaataa Haaromsi",
    areYouSureDeleteCar: "Konkolaataa kana kuusaa keessaa haquu kee mirkaneeffattee? Gochi kun hin deebi'u.",
    deleteCar: "Konkolaataa Haquu",

    // Admin Users
    userManagement: "Bulchiinsa Fayyadamtootaa",
    manageSystemAccess: "Akkasumas qooda fayyadamtootaa bulchi",
    searchUsersPrompt: "Fayyadamtoota maqaa ykn imeeliidhaan barbaadi...",
    userDetails: "Ibsa Fayyadamaa",
    loadingUserDatabase: "Kuusaa fayyadamtootaa fe'amaa jira...",
    noMatchingUsers: "Fayyadamaa walsimu hin argamne",
    suspendUser: "Fayyadamaa Hagugi",
    activateUser: "Fayyadamaa Bani",
    deleteAccount: "Herrega Haquu",
    areYouSureDeleteUser: "Fayyadamaa kana guutummaatti haquu kee mirkaneeffattee? Gochi kun hin deebi'u.",
    suspensionReason: "Sababa Hagugamuuf",
    confirmSuspension: "Hagugamuu Mirkaneessi",
    suspensionPrompt: "Maaloo sababa herrega kana hagugiteef ibsi. Fayyadamaan sun battalumatti ni dharramama.",

    // Admin Lottery
    lotteryManagement: "Bulchiinsa Lootarii",
    activeDraw: "Qurxii Hojii Irra Jiru",
    lotteryControl: "To'annaa Lootarii",
    activePrize: "Badhaasa Hojii Irra Jiru",
    range: "Daangaa",
    stopLottery: "Lootarii Dhaabi",
    numberRangeLabel: "Daangaa Lakkoofsaa",
    ticketPriceCalc: "Gatii Tikkeettii",
    initializeNewDraw: "Qurxii Haaraa Jalqabi",
    prepareForDraw: "Qurxiidhaaf Qophaa'i",
    drawWinnerDesc: "Erga lootariin cufamee fi kaffaltiin hundi mirkanaa'ee booda, hirmaattota mirkanaa'an keessaa carraan mo'ataa filachuu dandeessa.",
    drawTheWinner: "Mo'ataa Filadhu",
    lotteryConfirmed: "Mirkanaa'e",
    lotteryPending: "Eeggataa",
    lotteryFree: "Bilisa",

    // Admin Settings - General
    generalSettings: "Qindaa'ina Sirnaa Waliigalaa",
    platformName: "Maqaa Madalichaa",
    logo: "Loogoo",
    uploadLogo: "Loogoo Fe'i",
    defaultCurrency: "Maallaqa Idilee",
    defaultLanguage: "Afaan Idilee",
    timezone: "Naannoo Sa'aatii",
    dateFormat: "Bifa Guyyaa",
    contactInformation: "Odeeffannoo Quunnamtii",
    contactEmail: "Imeelii Quunnamtii",
    contactPhone: "Bilbila Quunnamtii",
    physicalAddress: "Teessoo",
    saveGeneralSettings: "Qindaa'ina Waliigalaa Olka'i",

    // Admin Settings - Security
    securityAccess: "Nageenya & Seensa",
    enableRegistration: "Galmee Fayyadamaa Hayyami",
    registrationDesc: "Fayyadamtoonni haaraan herrega akka uumaniif hayyami",
    minPasswordLength: "Dheerina Jecha Darbii Xiqqaa",
    sessionTimeout: "Yeroo Turtii (daqiiqaa)",
    requireUppercase: "Arfii Gurguddaa Gaafadhu",
    uppercaseDesc: "Jechi darbii yoo xiqqaate qubee guddaa tokko of keessaa qabaachuu qaba",
    requireNumbers: "Lakkoofsa Gaafadhu",
    numbersDesc: "Jechi darbii yoo xiqqaate lakkoofsa tokko of keessaa qabaachuu qaba",
    allowMultiLogin: "Seensa Hedduu Hayyami",
    multiLoginDesc: "Herregni tokko meeshaalee hedduu irratti akka seenu hayyami",
    saveSecuritySettings: "Qindaa'ina Nageenyaa Olka'i",

    // Admin Settings - Lottery
    lotteryModule: "Moojulii Lootarii",
    lotteryModuleDesc: "Yeroo dhaabatu, fayyadamtoonni lootarii ilaaluu, tikeetii bituu ykn kaffaltii fe'uu hin danda'an.",
    lotteryConfiguration: "Qindaa'ina Lootarii",
    drawFrequency: "Irra-deddeebii Qurxii",
    autoCloseLabel: "Qurxii Dura Ofumaan Cufuu (daqiiqaa)",
    staffPermissions: "Hayyama Hojjettoota Lootarii",
    paymentVerificationPerm: "Mirkaneessa Kaffaltii",
    numberGenPerm: "Madda Lakkoofsaa",
    adminOverridePerm: "Bulchiinsa Ol'aanaa",
    saveLotterySettings: "Qindaa'ina Lootarii Olka'i",

    // Admin Settings - Operational
    operationalControls: "To'annoo Hojii",
    operationalDesc: "Cufiinsa ariifataa ykn odiitiidhaaf furtuuwwan gurguddoo.",
    enableEntirePlatform: "Madalicha Guutuu Bani",
    platformShutdownDesc: "Cufuu jechuun fayyadamtoota hundaaf madalicha cufuu dha",
    maintenanceMessageLabel: "Ergaa Haala Suphaa",
    saveOperationalSettings: "Qindaa'ina Hojii Olka'i",

    // Admin Settings - Logs
    systemLogs: "Galmee Sirnaa",
    allActions: "Gochaawwan Hunda",
    adminOnly: "Bulchiinsa Qofa",
    staffOnly: "Hojjettoota Qofa",
    exportCSV: "CSV fe'i",
    noLogsFound: "Galmeen hin argamne.",

    // Admin Settings - Notifications
    notificationSettings: "Qindaa'ina Beeksisaa",
    emailNotifications: "Beeksisa Imeelii",
    smsNotifications: "Beeksisa SMS",
    largePaymentAlerts: "Beeksisa Kaffaltii Guddaa",
    suspiciousActivityAlerts: "Beeksisa Sochii Shakkisiisaa",
    saveNotificationSettings: "Qindaa'ina Beeksisaa Olka'i",

    // Admin Settings - Backup
    backupRecovery: "Olka'iinsa & Deebisanii Argachuu",
    backupFrequency: "Irra-deddeebii Olka'iinsaa",
    manualBackup: "Olka'iinsa Harkaa Jalqabi",
    remoteSnapshots: "SQL Snapshots",
    saveBackupSettings: "Qindaa'ina Olka'iinsaa Olka'i",

    // Admin Layout & Dashboard
    administration: "Bulchiinsa",
    exitAdmin: "Bulchiinsa keessaa ba'i",
    exitLotteryStaff: "Hojjetaa keessaa ba'i",
    lotteryPortal: "Toora Lootarii",
    adminCommandCenter: "Giddugala Bulchiinsaa",
    overviewMetrics: "Muzira Waliigalaa",
    live: "Dhugaa",
    review: "Sakatta'i",
    totalLabel: "Waliigala",
    est: "Tilmaama",
    platformConfiguration: "Qindaa'ina Madalichaa",
    settings: "Qindaa'ina",
    general: "Waliigala",
    security: "Nageenya",
    operational: "Hojii",
    logs: "Galmeewwan",
    notifications: "Beeksisa",
    backup: "Olka'iinsa",

    // Dashboard & Sidebar
    navGenerateNumbers: "Lakkoofsa Uumi",
    navLotteryPayments: "Kaffaltii Lootarii",
    navNumberBoard: "Gabatee Lakkoofsaa",
    navParticipants: "Hirmaattoota",
    navUsers: "Fayyadamaa",
    navManagementPortal: "Portaalii Bulchiinsaa",
    navCoreManagement: "Bulchiinsa Bu'uuraa",
    navLotteryOperations: "Hojiiwwan Lootarii",
    navTerminateSession: "Ba'i",
    navEngineHealthy: "Fayyaa",
    navStaffPortal: "Portaalii Hojjetaa",
    navGlobalAdmin: "Bulchaa Waliigalaa",
    navSystemId: "ID Sirnaa",
    navDashboard: "Daashboordii",

    // Notifications Page
    notifMarkAllAsRead: "Hunda dubbifame jedhi",
    notifLoading: "Beeksisa fidaa jira...",
    notifNoNotificationsYet: "Ammaaf beeksisni hin jiru",
    notifWhenUpdatesAppear: "Yeroo haareffamni jiraatu, asitti mul'ata.",
    notifMarkAsRead: "Dubbifame jedhi",
    notifDelete: "Haqi",

    // Admin Dashboard
    lotteryOpsPortal: "Portaalii Hojiiwwan Lootarii",
    dashAdminCommandCenter: "Jiddugala Ajaja Bulchiinsaa",
    platformRunningOpt: "Pilaatfoormiin kee haala gaariin hojjechaa jira. Gabaasa sochii dhiheenyaa armaan gadii ilaalaa.",
    systemSecure: "Sirni Nageenya Qaba",
    liveIntelligence: "Qorannoo Kallattii",
    realTimeData: "Daataa Yeroo Ammaa",
    actionRequired: "Tarkaanfiin Ni Barbaadama",
    fourThisWeek: "Torban kana +4",
    dashEstRevenue: "Tilmaama Galii",
    etbTotal: "Dimshaasha ETB",
    recentEvents: "Taateewwan Dhihoo",
    viewFullAudit: "Odiitii Guutuu Ilaali",
    gatheringLogs: "Galmeewwan sochii walitti qabaa jira...",
    newLotteryCreated: "Lootariin Haaraan Uumameera",
    securityPolicyUpdated: "Imaammanni Nageenyaa Haareffameera",
    paymentManualOverride: "Kaffaltiin Harkaan Fudhatame",
    adminDiagnosticsSweep: "Bulchaan qorannoo sirnaa guutuu raawwatee tikeetota eegaa jiran mirkaneesse.",
    operations: "Hojiiwwan",
    fastLotterySetup: "Qophii Lootarii Hatattamaa",
    initializationTools: "Meeshaalee Jalqabsiisuu",
    newDraw: "Qurxii Haaraa",

    // Admin Lottery Subpages
    alGenerateNumbers: "Lakkoofsa Uumi",
    alSetRangeAndPrize: "Daangaa lakkoofsaa fi badhaasa qindeesi — sirnichii tikeetii hunda yeruma sana uuma.",
    alMainPrize: "Badhaasa Guddaa",
    alTicketPriceSettings: "Gatiin Tikeetii Qindaa'ina Karaa",
    alPrizeExample: "Fkn: 2024 Toyota Camry",
    alInitializing: "Eegalaa jira...",
    alDrawingWinner: "Mo'ataa Filachaa jira...",
    alRequiresConfirmedTicket: "Qurxii gochuuf yoo xiqqaate kaffaltiin tikeetii 1 mirkanaa'uu qaba.",
    alOneLuckyWinner: "Nama carraa qabu tokkotu mo'ata! Dura kaffaltiin hunduu mirkanaa'uu isaa hubadhu.",
    
    lpLotteryParticipants: "Hirmaattoota Lootarii",
    lpActiveDraw: "Qurxii Ammaa:",
    lpSearchPlaceholder: "Maqaa ykn lakkoofsa tikeetiin barbaadi…",
    lpTotalParticipants: "Waliigala Hirmaattoota",
    lpConfirmedTickets: "Tikeetota Mirkanaa'an",
    lpPendingReview: "Ilaalcha Eegaa Jira",
    lpNoParticipantsMatching: "Hirmaataan barbaacha kee wajjin walsimu hin jiru.",
    lpNoVerifiedParticipants: "Hirmaataan mirkanaa'e ammaaf hin argamne.",
    lpParticipantsAppearOnce: "Kaffaltiin erga galfamee booda hirmaattoonni ni mul'atu.",
    lpParticipant: "Hirmaataa",
    lpTicketNumbers: "Lakkoofsa Tikeetii",
    lpCount: "Lakkoofsa",
    lpJoined: "Yeroo makame",
    lpShowingParticipants: "Argisiisaa jira",
    lpOf: "keessaa",
    lpClearSearch: "Barbaacha haqi",
    
    payLotteryPayments: "Kaffaltii Lootarii",
    payReviewVerify: "Ragaa kaffaltii tikeetii lootarii fayyadamtootaa ilaali mirkaneessi.",
    payRefresh: "Haaromsi",
    payAll: "Hunda",
    payTotal: "Ida'ama",
    payNoPaymentsFilter: "Kaffaltiin calaqa kee wajjin walsimu hin jiru.",
    payNoLotteryPayments: "Galmeen kaffaltii lootarii hin argamne.",
    payPaymentsAppearOnce: "Yeroo fayyadamtoonni ragaa kaffaltii isaanii galchan kaffaltiin ni mul'ata.",
    payUser: "Fayyadamaa",
    payMethod: "Akkaataa",
    payTicket: "Tikeetii",
    payReceipt: "Nagahee",
    payStatus: "Haala",
    payActions: "Tarkaanfiilee",
    payApprove: "Raggaasi",
    payReject: "Kuffisi",
    payView: "Ilaali",

    glNumberBoard: "Gabatee Lakkoofsaa",
    glLiveView: "Ilalcha kallattii lakkoofsa tikeetii hunda fi haala isaanii ammaa qurxii itti aanuuf.",
    glActiveDrawText: "Qurxii ammaa",
    glRangeText: "Daangaa",
    glNumbersGeneratedAuto: "Yeroo Bulchaan lootarii haaraa uumu lakkoofsonni of-umaan of uumu.",
    glTotalNumbers: "Waliigala Lakkoofsaa",
    glNoActiveLottery: "Lootariin amma hojjetu hin argamne.",
    glGoToLotteryManagement: "Qurxii haaraa uumuuf gara bulchiinsa lootarii deemi.",
    glNoNumbersMatch: "Lakkoofsi calaqa ammaa wajjin walsimu hin jiru.",

    // Lottery User Pages
    l_syncingDraw: "Qurxii kallattii wajjin walsimsiisaa jira...",
    l_platformVerified: "Pilaatfoormiin Mirkanaa'eera",
    l_premiumVehicleExp: "Muuxannoo Konkolaataa Gaarii",
    l_secureBlockchain: "Filannoo Nageenya Qabu",
    l_activeNow: "Ammaa Hojjechaa Jira",
    l_noActiveSweepstakes: "Lootariin Ammaa Hojjetu Hin Jiru",
    l_preparingNextDraw: "Qurxii guddaa itti aanu qopheessaa jirra. Maaloo dhihootti deebi'aa ilaalaa.",
    l_numbersReserved: "Lakkoofsoti Qabamaniiru",
    l_reservedSuccess: "Milkaa'inaan lakkoofsota qabattaniru:",
    l_finalizeEntry: "Nagahee keessan galchuun galmee keessan xumuraa.",
    l_backToLottery: "Gara Lootariitti Deebi'i",
    l_selectionStep: "Tarkaanfii Filannoo",
    l_pickLuckyPath: "Daandii carraa keetii filadhu",
    l_syncingBoard: "Gabatee Lakkoofsaa Walsimsiisaa Jira...",
    l_restrictedAccess: "Itti fayyadamni Daangeffameera",
    l_managementRestriction: "Akkaawuntiiwwan bulchiinsaa akka hirmaatan hin eyyamamu.",
    l_boardOffline: "Gabateen Toora Irraa Maqeera",

    // Profile Page
    logout: "Ba'umsaa",
    logoutSuccess: "Milkaa'inaan ba'ameera.",
    profileSynchronized: "Jijjiiramni milkaa'inaan kuufameera.",
    navTickets: "Tikeetii Koo",

    // Auth Extended
    authEncryptedAccess: "Bakka Seensaa Iccitii",
    authPremiumTitle: "PIRIIMIYEEMII KEESSAN",
    authJourneyStarts: "ADEEMSI ASITTI JALQABA.",
    authLoginDesc: "Daashboordii keessan arguuf, lootarii irratti hirmaachuuf fi fedhii keessan bulchuuf seenaa.",
    authVettedAssets: "Qabeenya Mirkanaa'e",
    authFairPlay: "Tapha Haqaa",
    authAuthenticatedAccess: "Seensa Mirkanaa'e",
    authEstablishingSession: "SEENSA UUMAA JIRA...",
    authWelcomeBackMsg: "Baga nagaan deebitan",
    authSecureSession: "Seensi nageenya qabu uumameera.",
    authAccessDenied: "Seensi Didameera",
    authNetworkError: "Dogoggora Nettarkii",
    authConnectionFailed: "Garuu seensi nageenya qabu hin milkoofne.",
    authInitializationIdentity: "EENYUMMAA JALQABSIISAA JIRA...",
    authSecureNodeInitialization: "Eenyummaa Nageenya Qabu Jalqabsiisuu",
    authJoinEliteNetwork: "NETWORK ELITE MAKAMA.",
    authRegisterDesc: "Carraa lootarii addaa, tajaajila kireeffannaa fi gabaa gurgurtaa konkolaataa argachuuf herrega uumaa.",
    authTransparentDraw: "Sirna Qurxii Ifa Ta'e",
    authVerifiedAssetNetwork: "Network Qabeenya Mirkanaa'e",
    authSeamlessAssetManagement: "Bulchiinsa Qabeenyaa Kee Haala Gaariin",
    authCreateIdentity: "Eenyummaa Uumi",
    authAccountInitialized: "Herregni Jalqabameera",
    authIdentityVerified: "Eenyummaan mirkanaa'eera. Amma seenuu dandeessu.",
    authRegistrationBlocked: "Galmeen Dhowwameera",
    authCredentialConflict: "Ragaan walsimu hin jiru.",
    authConnectionError: "Dogoggora Quunnamtii",
    authSecureNodeRegistration: "Galmeen nageenya qabu hin milkoofne.",

    // Payment Extended
    paySecureCheckout: "Kaffaltii Nageenya Qabu",
    payRestrictedAccess: "Seensa Daangeffame",
    payManagementRestriction: "Akaawuntiiwwan bulchiinsaa nageenya sirnaa eeguuf kaffaltii galchuu ykn lootarii irratti hirmaachuu hin danda'an.",
    paySelectionReservation: "Iddoo Qabame Filadhu",
    payWhichReservation: "Yeroo ammaa kaffaltii isa kam raawwachaa jirtu?",
    payNoReservedFound: "Lakkoofsi Qabame Hin Argamne",
    payPickConfirmNumbers: "Kaffaltii kaffaluun dura gabatee lootarii irratti lakkoofsa keessan filattanii mirkaneessuu qabdu.",
    payGoToBoard: "Gara Gabatee Lakkoofsaa Deemi",
    payAmountDue: "Maallaqa Kafalamu",
    payGateway: "Karaa Kaffaltii",
    payValidationMedia: "Miidiyaa Mirkaneessaa",
    payReplaceImage: "Suuraa Jijjiiri",
    payStreamingData: "DAATAA EGALAA JIRA...",
    payValidatingSession: "SEENSA MIRKANEESSAA JIRA...",
    payOfficialAccount: "Akkaawuntii Ofishilaa",
    payTransferInstructions: "Maaloo maallaqa tikeetii keessaniif barbaachisu sirriitti dabarsaa. Akkaawuntii dura mirkaneeffadhaa. Mirkaneessaaf suuraa qulqulluu qabu nuuf ergaa.",
    payCBE: "Baankii Daldala Itiyoophiyaa (CBE)",
    payTelebirrWallet: "Telebirr Wallet",
    payDriveHubAccount: "Drive Hub Lottery Account",
    payAdminTerminal: "Admin Payment Terminal",
    payRecentActivity: "Sochii Dhihoo",
    payFetchingLedger: "Muzira Fidaa Jira...",
    payNoTransactionHistory: "Seenaan Galmee Hin Argamne",
    payUnderReview: "Sakata'insa Irra Jira",
    payVerifyingReceipt: "Nagahee Mirkaneessaa",
    payAwaitingPayment: "Kaffaltii Eegaa Jira",
    payPaymentRejected: "Kaffaltiin Didameera",
    payTicketEntry: "Galfata Tikeetii",

    appSuffix: "Gurgurtaa fi Kireeffannaa Konkolaataa",

    // Admin Extended
    adminSystemCore: "bu'uura sirnaa",
    adminSettingsDesc: "Muuxannoo madalichaa fi ulaagaalee hojii sirreessi.",
    adminGeneralDesc: "Qindaa'ina bu'uuraa madalicha keetii.",
    adminSecurityDesc: "Imaammata jecha darbii fi amala seensaa dirqisiisi.",
    adminLotteryDesc: "Mekaaniikii ijoo fi gatii lootarii konkolaataa keetii.",
    adminOperationalDesc: "Furtuuwwan madalichaa fi haala suphaa haala ol'aanaatiin to'adhu.",
    adminNotificationsDesc: "Akkamitti fi yoom bulchitootaa fi fayyadamtootaaf beeksisni akka gahu to'adhu.",
    adminBackupDesc: "Daataa kee duumessa (cloud) irratti olka'uudhaan nageenya isaa eegsisdhu.",
    adminLogsDesc: "Hordoffii oديtii gochaawwan bulchiinsaa fi hojjettoota dhimma murteessoo irratti raawwataman.",
    adminStartingBackup: "Olka'iinsa Jalqabaa",
    adminTriggeringBackup: "Olka'iinsa kuusaa daataa harkaan jalqabsiisaa jira...",
    adminBackupFinalized: "Olka'iinsi Xumurameera",
    adminAccountRemoved: "Herregni milkaa'inaan haqameera.",
    role: "Gahee",
    adminConfirmSuspensionDesc: "Fayyadamaa kana haguguu kee mirkaneeffattee?",
    adminSuspensionReasonPlaceholder: "Fkn: Seera tajaajilaa cabsuu...",
    processing: "Hojjechaa jira...",
    generating: "Maddisiisaa jira...",
    profVerifiedProfile: "Profaayila Mirkanaa'e",
    profMemberSince: "Miseensa Madalichaa bara 2026 irraa jalqabee",
    profEntries: "Hirmaannaa",
    profRentals: "Kireeffannaa",
    profSave: "Olkaayi",
    profEdit: "Gulaali",
    profSecurityIdentity: "Nageenya fi Eenyummaa",
    profProfileConfiguration: "Qindaa'ina Profaayilaa",
    profFirstName: "Maqaa Jalqabaa",
    profLastName: "Maqaa Abbaa",
    profEmailTerminal: "Imeelii",
    profContactConnection: "Quunnamtii",
    profSyncChanges: "Jijjiirama Walitti Fiddu",
    profStatusLevel: "Sadarkaa Haalaa",
    profCoreContributor: "Gumaachaa Ijoo",
    profProgressToPlatinum: "Gara Sadarkaa Pilaatiinimii deemu",
    profRecentActivity: "Tarree Lootarii Dhihoo",
    profSynchronizedLedger: "Galmee Guutuu",
    profFinancialHistory: "Seenaa Faayinaansii fi Tookinii",
    profRequestingArchives: "Galmeewwan gaafachaa jira...",
    profNoActiveHistory: "Seenaan hojiirra jiru hin argamne",
    profStartJourney: "Lootariiwwan hojiirra jiran sakatta'uun imala kee jalqabi.",
    profExploreDraws: "ዕጣዎችን ያስሱ",
    profEndOfHistory: "Dhuma seenaa",
    profRequestAudit: "Daataa ooditii guutuu gaafadhu",
    profFleetAccess: "Seensa Konkolaataa",
    profActiveRentalContracts: "Waliigala waliigaltee kireeffannaa konkolaataa:",
    profManageFleet: "Konkolaataawwan Bulchi",
    profPendingEntry: "Eeggataa jira",
    profConfirmedEntry: "Galmee Mirkanaa'e",
    profRejectedEntry: "Kan Didame",
    profVerifyingReceipt: "Nagahee mirkaneessaa jira",
    profAwaitingPayment: "Kaffaltii eeggataa jira",
    profWinner: "MO'ATAA",
    profStandardEntry: "Galmee Hirmaannaa Lootarii",
    profPremiumUser: "Fayyadamaa Piriimiyeemii",
    profUserPlaceholder: "Fayyadamaa",
    profEmailPlaceholder: "user@email.com",
    profPhonePlaceholder: "+251 900 000 000",
  },
};
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("gech-lang");
    return (saved as Language) || "en";
  });

  const { settings } = useSettings();
  const { user, setUser } = useAuth();

  useEffect(() => {
    if (user?.language) {
      setLanguage(user.language as Language);
    } else {
      const saved = localStorage.getItem("gech-lang");
      const systemDefault = settings?.General?.defaultLanguage as Language;
      
      // Only force external settings if user hasn't made a choice yet
      if (systemDefault && !saved) {
        setLanguage(systemDefault);
      }
    }
  }, [user?.language, settings?.General?.defaultLanguage]);

  const handleSetLanguage = async (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("gech-lang", lang);
    if (user) {
      setUser({ ...user, language: lang });
      try {
        await apiFetch("/auth/language", {
          method: "PATCH",
          body: JSON.stringify({ language: lang }),
        });
      } catch (err) {
        console.error("Failed to sync language preference", err);
      }
    }
  };

  const t = (key: string) => {
    const translation = translations[language]?.[key] || translations.en[key];
    if (!translation) {
      // console.warn(`Missing translation for key: ${key}`);
      return key;
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
